"use client";
import { useEffect, useState } from "react";
import { emptyPortfolioContent, PORTFOLIO_ENTRY_FIELDS, PORTFOLIO_PROFILE_FIELDS, PORTFOLIO_SECTIONS, portfolioErrorMessage, updatePortfolioEntry, type PortfolioContent, type PortfolioDraft } from "@aperture/portfolio";
import { usePortfolio } from "./provider";
import styles from "./portfolio.module.css";
export function PortfolioEditor() {
  const { ownerId, service } = usePortfolio(); const [draft, setDraft] = useState<PortfolioDraft | null>(null); const [content, setContent] = useState<PortfolioContent>(emptyPortfolioContent); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState(""); const [confirmation, setConfirmation] = useState("");
  const apply = (value: PortfolioDraft) => { setDraft(value); setContent(value.content); };
  useEffect(() => { let active = true; void service.getDraft(ownerId).then((value) => { if (active) { setDraft(value); setContent(value.content); } }).catch((failure: unknown) => { if (active) setError(portfolioErrorMessage(failure)); }); return () => { active = false; }; }, [ownerId, service]);
  async function perform(work: () => Promise<PortfolioDraft>, success: string) { setBusy(true); setError(null); setMessage(""); try { apply(await work()); setMessage(success); } catch (failure) { setError(portfolioErrorMessage(failure)); } finally { setBusy(false); } }
  return <main className={styles.editor}><header><p className={styles.eyebrow}>PRIVATE PORTFOLIO EDITOR</p><h1>Curate your professional story</h1><p>Only content you write here can appear publicly. Dashboard records and your account email are never copied.</p></header>
    {error ? <p className={styles.error} role="alert">{error}</p> : null}{message ? <p role="status">{message}</p> : null}
    <div className={styles.actions}><button disabled={busy} onClick={() => void perform(() => service.getDraft(ownerId), "Latest draft loaded. Unsaved edits were replaced.")}>Reload saved draft</button><button disabled={busy || draft === null} onClick={() => void perform(() => service.saveDraft(ownerId, content, draft!.revision), "Private draft saved.")}>Save private draft</button></div>
    {draft === null ? <p role="status">{error ? "Reload to recover the draft." : "Loading portfolio…"}</p> : <>
      <section className={styles.card}><h2>Profile & biography</h2>{PORTFOLIO_PROFILE_FIELDS.map(({ key, label }) => <label className={styles.field} key={key}><span>{label}</span>{key === "biography" ? <textarea aria-label={label} rows={5} value={content.profile[key]} onChange={(event) => setContent({ ...content, profile: { ...content.profile, [key]: event.target.value } })} /> : <input aria-label={label} value={content.profile[key]} onChange={(event) => setContent({ ...content, profile: { ...content.profile, [key]: event.target.value } })} />}</label>)}<label className={styles.field}><span>Resume HTTPS link</span><input aria-label="Resume link" value={content.resumeUrl} onChange={(event) => setContent({ ...content, resumeUrl: event.target.value })} /></label></section>
      {PORTFOLIO_SECTIONS.map((section) => <section className={styles.card} key={section.key}><h2>{section.title}</h2>{section.key === "educationHighlights" ? <p>Write only achievements you explicitly choose to share. No academic record is imported automatically.</p> : null}{section.key === "contactLinks" ? <p>A mailto address appears publicly only if you explicitly enter it here.</p> : null}
        {content[section.key].length === 0 ? <p className={styles.muted}>No {section.title.toLowerCase()} added.</p> : null}
        {content[section.key].map((entry, index) => <fieldset className={styles.entry} key={entry.id}><legend>{section.title} {index + 1}</legend>{PORTFOLIO_ENTRY_FIELDS.map(({ key, label }) => <label className={styles.field} key={key}><span>{key === "title" ? section.itemLabel : key === "subtitle" ? section.subtitleLabel : label}</span><input aria-label={`${section.title} ${index + 1} ${label}`} value={entry[key]} onChange={(event) => setContent(updatePortfolioEntry(content, section.key, entry.id, key, event.target.value))} /></label>)}<button onClick={() => setContent({ ...content, [section.key]: content[section.key].filter((row) => row.id !== entry.id) })}>Remove {section.title.toLowerCase()} {index + 1}</button></fieldset>)}
        <button onClick={() => setContent({ ...content, [section.key]: [...content[section.key], service.createEntry()] })}>Add {section.title.toLowerCase()}</button>
      </section>)}
      <section className={styles.card}><h2>Publication controls</h2><p>{draft.publication === null ? "No public snapshot is prepared." : `Snapshot prepared ${draft.publication.publishedAt}. Later draft edits stay private until you prepare another snapshot.`}</p><p>The public /portfolio page remains unavailable until the operator explicitly enables publication in server configuration. Saving this draft does not publish it.</p><label className={styles.field}><span>Type PUBLISH PORTFOLIO {ownerId}</span><input aria-label="Publication confirmation" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><div className={styles.actions}><button disabled={busy} onClick={() => void perform(async () => { const saved = await service.saveDraft(ownerId, content, draft.revision); apply(saved); return service.preparePublication(ownerId, saved.revision, confirmation); }, "Curated snapshot prepared. Server publication configuration still applies.")}>Prepare public snapshot</button><button disabled={busy || draft.publication === null} onClick={() => void perform(() => service.unpublish(ownerId, draft.revision), "Public snapshot removed.")}>Unpublish</button></div><a href="/portfolio">Open public presentation</a></section>
    </>}
  </main>;
}
