import type { PublicPortfolio } from "@aperture/portfolio";
import styles from "./portfolio.module.css";
export function PortfolioPresentation({ snapshot }: { readonly snapshot: PublicPortfolio }) {
  const { content } = snapshot;
  return <main className={styles.public}><a className={styles.skip} href="#portfolio-content">Skip to portfolio content</a><header className={styles.hero}><p className={styles.eyebrow}>PROFESSIONAL PORTFOLIO</p><h1>{content.profile.displayName}</h1><p className={styles.headline}>{content.profile.headline}</p>{content.profile.location ? <p>{content.profile.location}</p> : null}<nav aria-label="Portfolio contact links" className={styles.actions}>{content.contactLinks.map((link) => <a key={link.id} href={link.url} rel="noopener noreferrer">{link.title}</a>)}{content.resumeUrl ? <a href={content.resumeUrl} rel="noopener noreferrer">View resume</a> : null}</nav></header>
    <div id="portfolio-content" className={styles.content}><section className={styles.card}><h2>About</h2><p className={styles.biography}>{content.profile.biography}</p></section>
      {content.skills.length ? <section className={styles.card}><h2>Skills</h2><ul className={styles.skills}>{content.skills.map((skill) => <li key={skill.id}><strong>{skill.title}</strong>{skill.subtitle ? <span>{skill.subtitle}</span> : null}</li>)}</ul></section> : null}
      {([{ key: "projects", title: "Projects" }, { key: "experience", title: "Experience" }, { key: "educationHighlights", title: "Education highlights" }, { key: "certifications", title: "Certifications" }] as const).map(({ key, title }) => content[key].length ? <section className={styles.section} key={key}><h2>{title}</h2><div className={styles.grid}>{content[key].map((entry) => <article className={styles.card} key={entry.id}><h3>{entry.title}</h3>{entry.subtitle ? <p className={styles.subtitle}>{entry.subtitle}</p> : null}{entry.period ? <p className={styles.muted}>{entry.period}</p> : null}{entry.description ? <p className={styles.biography}>{entry.description}</p> : null}{entry.url ? <a href={entry.url} rel="noopener noreferrer">View {entry.title}</a> : null}</article>)}</div></section> : null)}
    </div><footer className={styles.footer}>Independently curated professional information.</footer></main>;
}
