import * as health from "@aperture/health";
import type { ZodType } from "@aperture/validation";

export const enumCases: readonly { name: string; schema: ZodType<unknown>; values: readonly string[] }[] = [
  { name: "weightUnitSchema", schema: health.weightUnitSchema, values: ["kilogram","pound"] },
  { name: "heightUnitSchema", schema: health.heightUnitSchema, values: ["centimeter","inch"] },
  { name: "distanceUnitSchema", schema: health.distanceUnitSchema, values: ["meter","kilometer","foot","mile"] },
  { name: "durationUnitSchema", schema: health.durationUnitSchema, values: ["second","minute","hour"] },
  { name: "paceUnitSchema", schema: health.paceUnitSchema, values: ["seconds_per_kilometer","seconds_per_mile"] },
  { name: "speedUnitSchema", schema: health.speedUnitSchema, values: ["kilometers_per_hour","miles_per_hour","meters_per_second"] },
  { name: "temperatureUnitSchema", schema: health.temperatureUnitSchema, values: ["celsius","fahrenheit"] },
  { name: "energyUnitSchema", schema: health.energyUnitSchema, values: ["kilocalorie","kilojoule"] },
  { name: "hydrationVolumeUnitSchema", schema: health.hydrationVolumeUnitSchema, values: ["milliliter","liter","fluid_ounce"] },
  { name: "nutritionMassUnitSchema", schema: health.nutritionMassUnitSchema, values: ["milligram","gram","ounce"] },
  { name: "bloodGlucoseUnitSchema", schema: health.bloodGlucoseUnitSchema, values: ["milligrams_per_deciliter","millimoles_per_liter"] },
  { name: "workoutLoadUnitSchema", schema: health.workoutLoadUnitSchema, values: ["kilogram_repetition","pound_repetition"] },
  { name: "healthErrorCodeSchema", schema: health.healthErrorCodeSchema, values: ["not_found","conflict","invalid_state","unsupported_operation"] },
  { name: "measurementSystemSchema", schema: health.measurementSystemSchema, values: ["metric","imperial"] },
  { name: "recordStatusSchema", schema: health.recordStatusSchema, values: ["active","archived"] },
  { name: "appointmentStatusSchema", schema: health.appointmentStatusSchema, values: ["scheduled","cancelled","completed"] },
  { name: "equipmentCategorySchema", schema: health.equipmentCategorySchema, values: ["running_shoes","strength","cardio","mobility","other"] },
  { name: "equipmentStatusSchema", schema: health.equipmentStatusSchema, values: ["active","retired"] },
  { name: "exerciseCategorySchema", schema: health.exerciseCategorySchema, values: ["strength","cardio","mobility","balance","other"] },
  { name: "exerciseStatusSchema", schema: health.exerciseStatusSchema, values: ["active","archived"] },
  { name: "healthMeasurementTypeSchema", schema: health.healthMeasurementTypeSchema, values: ["weight","height","waist","hip"] },
  { name: "medicationLogStatusSchema", schema: health.medicationLogStatusSchema, values: ["taken","skipped"] },
  { name: "medicationStatusSchema", schema: health.medicationStatusSchema, values: ["active","archived"] },
  { name: "mealTypeSchema", schema: health.mealTypeSchema, values: ["breakfast","lunch","dinner","snack","other"] },
  { name: "healthProfileStatusSchema", schema: health.healthProfileStatusSchema, values: ["active","archived"] },
  { name: "runningActivityStatusSchema", schema: health.runningActivityStatusSchema, values: ["planned","in_progress","completed"] },
  { name: "sleepQualitySchema", schema: health.sleepQualitySchema, values: ["poor","fair","good","excellent"] },
  { name: "workoutPlanStatusSchema", schema: health.workoutPlanStatusSchema, values: ["draft","active","archived"] },
  { name: "workoutSessionStatusSchema", schema: health.workoutSessionStatusSchema, values: ["planned","in_progress","paused","completed","cancelled"] },
  { name: "vitalReadingTypeSchema", schema: health.vitalReadingTypeSchema, values: ["resting_heart_rate","blood_pressure","blood_glucose","oxygen_saturation","body_temperature"] },
  { name: "heartRateUnitSchema", schema: health.heartRateUnitSchema, values: ["beats_per_minute"] },
  { name: "bloodPressureUnitSchema", schema: health.bloodPressureUnitSchema, values: ["millimeters_of_mercury"] },
  { name: "oxygenSaturationUnitSchema", schema: health.oxygenSaturationUnitSchema, values: ["percent"] },
  { name: "percentageUnitSchema", schema: health.percentageUnitSchema, values: ["percent"] },
  { name: "repetitionUnitSchema", schema: health.repetitionUnitSchema, values: ["repetition"] },
  { name: "heartRateVariabilityUnitSchema", schema: health.heartRateVariabilityUnitSchema, values: ["millisecond"] },
];

export const identifierCases = [
  { name: "OwnerId", schema: health.ownerIdSchema },
  { name: "AppointmentId", schema: health.appointmentIdSchema },
  { name: "BodyCompositionRecordId", schema: health.bodyCompositionRecordIdSchema },
  { name: "EquipmentId", schema: health.equipmentIdSchema },
  { name: "ExerciseSetId", schema: health.exerciseSetIdSchema },
  { name: "ExerciseId", schema: health.exerciseIdSchema },
  { name: "HydrationEntryId", schema: health.hydrationEntryIdSchema },
  { name: "LaboratoryResultId", schema: health.laboratoryResultIdSchema },
  { name: "HealthMeasurementId", schema: health.healthMeasurementIdSchema },
  { name: "MedicationLogId", schema: health.medicationLogIdSchema },
  { name: "MedicationId", schema: health.medicationIdSchema },
  { name: "NutritionEntryId", schema: health.nutritionEntryIdSchema },
  { name: "PersonalRecordId", schema: health.personalRecordIdSchema },
  { name: "HealthProfileId", schema: health.healthProfileIdSchema },
  { name: "RecoveryEntryId", schema: health.recoveryEntryIdSchema },
  { name: "ActivityRouteId", schema: health.activityRouteIdSchema },
  { name: "RunningActivityId", schema: health.runningActivityIdSchema },
  { name: "RunningSplitId", schema: health.runningSplitIdSchema },
  { name: "SleepRecordId", schema: health.sleepRecordIdSchema },
  { name: "SymptomEntryId", schema: health.symptomEntryIdSchema },
  { name: "VitalReadingId", schema: health.vitalReadingIdSchema },
  { name: "WorkoutPlanId", schema: health.workoutPlanIdSchema },
  { name: "WorkoutSessionId", schema: health.workoutSessionIdSchema },
];
