import { expect, expectTypeOf, it } from "vitest";
import * as health from "@aperture/health";
import type { HealthRepository, HealthService, HealthProfile, HealthProfileId, UpdateExerciseSetInput, VitalReadingValue } from "@aperture/health";
import type { calculateBmi, createHealthProfile } from "@aperture/health/contracts";

const expectedExports = [
  "activityRouteIdSchema",
  "activityRouteListQuerySchema",
  "activityRouteSchema",
  "appointmentIdSchema",
  "appointmentListQuerySchema",
  "appointmentSchema",
  "appointmentStatusSchema",
  "bloodGlucoseUnitSchema",
  "bloodGlucoseValueSchema",
  "bloodPressureUnitSchema",
  "bloodPressureValueSchema",
  "bodyCompositionListQuerySchema",
  "bodyCompositionRecordIdSchema",
  "bodyCompositionRecordSchema",
  "createActivityRouteInputSchema",
  "createAppointmentInputSchema",
  "createEquipmentInputSchema",
  "createExerciseInputSchema",
  "createHealthProfileInputSchema",
  "createMedicationInputSchema",
  "createNutritionEntryInputSchema",
  "createRunningActivityInputSchema",
  "createWorkoutPlanInputSchema",
  "createWorkoutSessionInputSchema",
  "dateRangeSchema",
  "decimalStringSchema",
  "distanceUnitSchema",
  "distanceValueSchema",
  "durationUnitSchema",
  "durationValueSchema",
  "energyUnitSchema",
  "energyValueSchema",
  "entityMetadataSchema",
  "equipmentCategorySchema",
  "equipmentIdSchema",
  "equipmentListQuerySchema",
  "equipmentSchema",
  "equipmentStatusSchema",
  "equipmentUsageSummarySchema",
  "exerciseCategorySchema",
  "exerciseIdSchema",
  "exerciseListQuerySchema",
  "exerciseSchema",
  "exerciseSetIdSchema",
  "exerciseSetListQuerySchema",
  "exerciseSetSchema",
  "exerciseSetsByExerciseQuerySchema",
  "exerciseSetsByWorkoutQuerySchema",
  "exerciseStatusSchema",
  "exercisesByCategoryQuerySchema",
  "healthDomainErrorSchema",
  "healthErrorCodeSchema",
  "healthMeasurementIdSchema",
  "healthMeasurementListQuerySchema",
  "healthMeasurementSchema",
  "healthMeasurementTypeSchema",
  "healthMeasurementValueSchema",
  "healthMeasurementsByDateRangeQuerySchema",
  "healthMeasurementsByTypeQuerySchema",
  "healthProfileIdSchema",
  "healthProfileSchema",
  "healthProfileStatusSchema",
  "heartRateUnitSchema",
  "heartRateValueSchema",
  "heartRateVariabilityUnitSchema",
  "heartRateVariabilityValueSchema",
  "heightUnitSchema",
  "heightValueSchema",
  "hydrationEntriesByDateQuerySchema",
  "hydrationEntryIdSchema",
  "hydrationEntryListQuerySchema",
  "hydrationEntrySchema",
  "hydrationVolumeUnitSchema",
  "hydrationVolumeValueSchema",
  "identifierSchema",
  "isoDateSchema",
  "isoDateStringSchema",
  "isoDateTimeSchema",
  "isoDateTimeStringSchema",
  "laboratoryResultIdSchema",
  "laboratoryResultListQuerySchema",
  "laboratoryResultSchema",
  "laboratoryResultValueSchema",
  "mealTypeSchema",
  "measurementSystemSchema",
  "medicationIdSchema",
  "medicationListQuerySchema",
  "medicationLogIdSchema",
  "medicationLogListQuerySchema",
  "medicationLogSchema",
  "medicationLogStatusSchema",
  "medicationSchema",
  "medicationStatusSchema",
  "nutritionEntriesByDateQuerySchema",
  "nutritionEntryIdSchema",
  "nutritionEntryListQuerySchema",
  "nutritionEntrySchema",
  "nutritionMassUnitSchema",
  "nutritionMassValueSchema",
  "ownerIdSchema",
  "ownerQuerySchema",
  "oxygenSaturationUnitSchema",
  "oxygenSaturationValueSchema",
  "paceUnitSchema",
  "paceValueSchema",
  "pageRequestSchema",
  "pageResultSchema",
  "perceivedEffortSchema",
  "percentageUnitSchema",
  "percentageValueSchema",
  "personalRecordIdSchema",
  "personalRecordListQuerySchema",
  "personalRecordMetricSchema",
  "personalRecordSchema",
  "recordBodyCompositionInputSchema",
  "recordEquipmentUsageInputSchema",
  "recordExerciseSetInputSchema",
  "recordHealthMeasurementInputSchema",
  "recordHydrationInputSchema",
  "recordLaboratoryResultInputSchema",
  "recordMedicationLogInputSchema",
  "recordPersonalRecordInputSchema",
  "recordRecoveryEntryInputSchema",
  "recordRunningSplitInputSchema",
  "recordSleepInputSchema",
  "recordStatusSchema",
  "recordSymptomInputSchema",
  "recordVitalReadingInputSchema",
  "recoveryEntryIdSchema",
  "recoveryEntryListQuerySchema",
  "recoveryEntrySchema",
  "recoveryRatingSchema",
  "repetitionCountSchema",
  "repetitionUnitSchema",
  "repositoryFilterSchema",
  "runningActivitiesByDateRangeQuerySchema",
  "runningActivityIdSchema",
  "runningActivityListQuerySchema",
  "runningActivitySchema",
  "runningActivityStatusSchema",
  "runningSplitIdSchema",
  "runningSplitListQuerySchema",
  "runningSplitSchema",
  "runningSplitsByActivityQuerySchema",
  "sleepQualitySchema",
  "sleepRecordIdSchema",
  "sleepRecordListQuerySchema",
  "sleepRecordSchema",
  "sleepRecordsByDateRangeQuerySchema",
  "speedUnitSchema",
  "speedValueSchema",
  "symptomEntryIdSchema",
  "symptomEntryListQuerySchema",
  "symptomEntrySchema",
  "symptomSeveritySchema",
  "temperatureUnitSchema",
  "temperatureValueSchema",
  "upcomingAppointmentsQuerySchema",
  "updateActivityRouteInputSchema",
  "updateAppointmentInputSchema",
  "updateBodyCompositionInputSchema",
  "updateEquipmentInputSchema",
  "updateExerciseInputSchema",
  "updateExerciseSetInputSchema",
  "updateHealthMeasurementInputSchema",
  "updateHealthProfileInputSchema",
  "updateHydrationEntryInputSchema",
  "updateLaboratoryResultInputSchema",
  "updateMedicationInputSchema",
  "updateMedicationLogInputSchema",
  "updateNutritionEntryInputSchema",
  "updatePersonalRecordInputSchema",
  "updateRecoveryEntryInputSchema",
  "updateRunningActivityInputSchema",
  "updateRunningSplitInputSchema",
  "updateSleepInputSchema",
  "updateSymptomEntryInputSchema",
  "updateVitalReadingInputSchema",
  "updateWorkoutPlanInputSchema",
  "updateWorkoutSessionInputSchema",
  "vitalReadingIdSchema",
  "vitalReadingListQuerySchema",
  "vitalReadingSchema",
  "vitalReadingTypeSchema",
  "vitalReadingValueSchema",
  "vitalReadingsByDateRangeQuerySchema",
  "vitalReadingsByTypeQuerySchema",
  "weightUnitSchema",
  "weightValueSchema",
  "workoutLoadUnitSchema",
  "workoutLoadValueSchema",
  "workoutPlanIdSchema",
  "workoutPlanListQuerySchema",
  "workoutPlanSchema",
  "workoutPlanStatusSchema",
  "workoutSessionIdSchema",
  "workoutSessionListQuerySchema",
  "workoutSessionSchema",
  "workoutSessionStatusSchema",
  "workoutSessionsByDateRangeQuerySchema"
] as const;

it("exposes the complete Phase 11 surface through the built package", () => {
  expect(Object.keys(health).sort()).toEqual([...expectedExports].sort());
  for (const key of expectedExports) expect(health[key]).toBeDefined();
});

it("retains inferred and deferred public types", () => {
  expectTypeOf<HealthProfileId>().toEqualTypeOf<string>();
  expectTypeOf<ReturnType<typeof health.healthProfileSchema.parse>>().toMatchTypeOf<HealthProfile>();
  expectTypeOf<UpdateExerciseSetInput>().not.toHaveProperty("ownerId");
  expectTypeOf<UpdateExerciseSetInput>().not.toHaveProperty("exerciseId");
  expectTypeOf<HealthRepository>().toHaveProperty("profiles");
  expectTypeOf<HealthService>().toHaveProperty("getHealthOverview");
  expectTypeOf<typeof calculateBmi>().toBeFunction();
  expectTypeOf<typeof createHealthProfile>().toBeFunction();
  const reading: VitalReadingValue = health.vitalReadingValueSchema.parse({ type: "blood_pressure", value: { systolic: 1, diastolic: 1, unit: "millimeters_of_mercury" } });
  if (reading.type === "blood_pressure") expectTypeOf(reading.value.systolic).toEqualTypeOf<number>();
});

it("preserves readonly nested quantities in both inferred types and parsed values", () => {
  const parsed = health.recordHydrationInputSchema.parse({
    ownerId: "synthetic-owner", volume: { value: "1.00", unit: "liter" },
    consumedAt: "2040-01-01T00:00:00Z",
  });
  expectTypeOf(parsed.volume).toEqualTypeOf<health.HydrationVolumeValue>();
  expect(Object.isFrozen(parsed)).toBe(true);
  expect(Object.isFrozen(parsed.volume)).toBe(true);
  expect(Reflect.set(parsed.volume, "value", "2")).toBe(false);
  expect(parsed.volume.value).toBe("1.00");
});
