/* This file is generated by scripts/generate-calculator-registry.mjs. Do not edit directly. */
import { inflationAdjustedValuePlugin } from "./economic/inflation-adjustment.plugin.js";
import { gstPlugin } from "./income-tax/gst.plugin.js";
import { hraPlugin } from "./income-tax/hra.plugin.js";
import { incomeTaxPlugin } from "./income-tax/income-tax.plugin.js";
import { netSalaryPlugin } from "./income-tax/salary.plugin.js";
import { tdsPlugin } from "./income-tax/tds.plugin.js";
import { brokeragePlugin } from "./investments/brokerage.plugin.js";
import { cagrPlugin } from "./investments/cagr.plugin.js";
import { fdPlugin } from "./investments/fd.plugin.js";
import { lumpsumPlugin } from "./investments/lumpsum.plugin.js";
import { marginPlugin } from "./investments/margin.plugin.js";
import { mutualFundReturnsPlugin } from "./investments/mutual-fund.plugin.js";
import { nscPlugin } from "./investments/nsc.plugin.js";
import { postOfficeMisPlugin } from "./investments/post-office-mis.plugin.js";
import { ppfPlugin } from "./investments/ppf.plugin.js";
import { rdPlugin } from "./investments/rd.plugin.js";
import { roiPlugin } from "./investments/roi.plugin.js";
import { scssPlugin } from "./investments/scss.plugin.js";
import { sipPlugin } from "./investments/sip.plugin.js";
import { ssyPlugin } from "./investments/ssy.plugin.js";
import { stepUpSipPlugin } from "./investments/step-up-sip.plugin.js";
import { stockAveragePlugin } from "./investments/stock-average.plugin.js";
import { swpPlugin } from "./investments/swp.plugin.js";
import { xirrPlugin } from "./investments/xirr.plugin.js";
import { carLoanEmiPlugin } from "./loans/car-loan-emi.plugin.js";
import { compoundInterestPlugin } from "./loans/compound-interest.plugin.js";
import { emiPlugin } from "./loans/emi.plugin.js";
import { flatVsReducingRatePlugin } from "./loans/flat-vs-reducing-rate.plugin.js";
import { homeLoanEmiPlugin } from "./loans/home-loan-emi.plugin.js";
import { simpleInterestPlugin } from "./loans/simple-interest.plugin.js";
import { apyPlugin } from "./retirement/apy.plugin.js";
import { epfPlugin } from "./retirement/epf.plugin.js";
import { firePlugin } from "./retirement/fire.plugin.js";
import { gratuityPlugin } from "./retirement/gratuity.plugin.js";
import { npsPlugin } from "./retirement/nps.plugin.js";
import { retirementCorpusPlugin } from "./retirement/retirement-corpus.plugin.js";

export * from "./economic/inflation-adjustment.plugin.js";
export * from "./income-tax/gst.plugin.js";
export * from "./income-tax/hra.plugin.js";
export * from "./income-tax/income-tax.plugin.js";
export * from "./income-tax/salary.plugin.js";
export * from "./income-tax/tds.plugin.js";
export * from "./investments/brokerage.plugin.js";
export * from "./investments/cagr.plugin.js";
export * from "./investments/fd.plugin.js";
export * from "./investments/lumpsum.plugin.js";
export * from "./investments/margin.plugin.js";
export * from "./investments/mutual-fund.plugin.js";
export * from "./investments/nsc.plugin.js";
export * from "./investments/post-office-mis.plugin.js";
export * from "./investments/ppf.plugin.js";
export * from "./investments/rd.plugin.js";
export * from "./investments/roi.plugin.js";
export * from "./investments/scss.plugin.js";
export * from "./investments/sip.plugin.js";
export * from "./investments/ssy.plugin.js";
export * from "./investments/step-up-sip.plugin.js";
export * from "./investments/stock-average.plugin.js";
export * from "./investments/swp.plugin.js";
export * from "./investments/xirr.plugin.js";
export * from "./loans/car-loan-emi.plugin.js";
export * from "./loans/compound-interest.plugin.js";
export * from "./loans/emi.plugin.js";
export * from "./loans/flat-vs-reducing-rate.plugin.js";
export * from "./loans/home-loan-emi.plugin.js";
export * from "./loans/simple-interest.plugin.js";
export * from "./retirement/apy.plugin.js";
export * from "./retirement/epf.plugin.js";
export * from "./retirement/fire.plugin.js";
export * from "./retirement/gratuity.plugin.js";
export * from "./retirement/nps.plugin.js";
export * from "./retirement/retirement-corpus.plugin.js";

export const allFinanceCalculatorPlugins = Object.freeze([
  inflationAdjustedValuePlugin,
  gstPlugin,
  hraPlugin,
  incomeTaxPlugin,
  netSalaryPlugin,
  tdsPlugin,
  brokeragePlugin,
  cagrPlugin,
  fdPlugin,
  lumpsumPlugin,
  marginPlugin,
  mutualFundReturnsPlugin,
  nscPlugin,
  postOfficeMisPlugin,
  ppfPlugin,
  rdPlugin,
  roiPlugin,
  scssPlugin,
  sipPlugin,
  ssyPlugin,
  stepUpSipPlugin,
  stockAveragePlugin,
  swpPlugin,
  xirrPlugin,
  carLoanEmiPlugin,
  compoundInterestPlugin,
  emiPlugin,
  flatVsReducingRatePlugin,
  homeLoanEmiPlugin,
  simpleInterestPlugin,
  apyPlugin,
  epfPlugin,
  firePlugin,
  gratuityPlugin,
  npsPlugin,
  retirementCorpusPlugin,
]);

const calculatorIds = new Set(allFinanceCalculatorPlugins.map((plugin) => plugin.manifest.id));
if (calculatorIds.size !== allFinanceCalculatorPlugins.length) throw new Error("Finance calculator identifiers must be unique.");

export const investmentCalculatorPlugins = Object.freeze(allFinanceCalculatorPlugins.filter((plugin) => plugin.manifest.category === "investment"));
export const loanCalculatorPlugins = Object.freeze(allFinanceCalculatorPlugins.filter((plugin) => plugin.manifest.category === "loan"));
export const incomeTaxCalculatorPlugins = Object.freeze(allFinanceCalculatorPlugins.filter((plugin) => plugin.manifest.category === "income_tax"));
export const economicCalculatorPlugins = Object.freeze(allFinanceCalculatorPlugins.filter((plugin) => plugin.manifest.category === "economic"));
export const retirementCalculatorPlugins = Object.freeze(allFinanceCalculatorPlugins.filter((plugin) => plugin.manifest.category === "retirement"));

export function getFinanceCalculatorPlugin(id: string) {
  return allFinanceCalculatorPlugins.find((plugin) => plugin.manifest.id === id);
}

export function getInvestmentCalculatorPlugin(id: string) {
  return investmentCalculatorPlugins.find((plugin) => plugin.manifest.id === id);
}

export function getRetirementCalculatorPlugin(id: string) {
  return retirementCalculatorPlugins.find((plugin) => plugin.manifest.id === id);
}
