"use client";

import { useCallback, useMemo, useState, type FormEvent } from "react";
import type { Assignment, Course } from "@aperture/education";
import { useEducation } from "../providers/education-provider";
import { useEducationAction } from "../hooks/use-education-action";
import { useEducationQuery } from "../hooks/use-education-query";
import { EmptyState, ErrorBanner, LoadingState, PageHeader, Panel, SelectInput, StatusBadge, SubmitButton, TextInput, formatDateTime, toIsoTimestamp } from "../components/ui";

interface AssignmentData { readonly courses: readonly Course[]; readonly assignments: readonly Assignment[]; }

export function AssignmentsScreen() {
  const { service, context, clock } = useEducation(); const action = useEducationAction();
  const load = useCallback(async (): Promise<AssignmentData> => { const [courses, assignments] = await Promise.all([service.listCourses(context), service.listAssignments(context)]); return { courses: courses.items, assignments: assignments.items }; }, [service, context]);
  const query = useEducationQuery(load);
  const [courseFilter, setCourseFilter] = useState(""); const [statusFilter, setStatusFilter] = useState("");
  const visible = useMemo(() => (query.data?.assignments ?? []).filter((item) => (!courseFilter || item.courseId === courseFilter) && (!statusFilter || item.status === statusFilter)), [query.data, courseFilter, statusFilter]);
  const courseName = (id: string) => query.data?.courses.find((item) => item.id === id)?.name ?? "Unknown course";
  return <><PageHeader eyebrow="Deadlines" title="Assignments" description="Capture coursework, inspect due dates, and move each assignment through the service-defined lifecycle." />
    <div className="grid grid-2"><AssignmentForm courses={query.data?.courses ?? []} /><Panel title="Assignment list" description="Overdue items are identified from the injected preview clock.">
      <div className="filters"><SelectInput name="assignmentCourseFilter" label="Course" value={courseFilter} onChange={(event) => setCourseFilter(event.target.value)}><option value="">All courses</option>{query.data?.courses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectInput><SelectInput name="assignmentStatusFilter" label="Status" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="">All statuses</option>{["draft","assigned","submitted","completed","cancelled"].map((value) => <option key={value} value={value}>{value}</option>)}</SelectInput></div>
      <ErrorBanner error={query.error ?? action.error} />{query.loading ? <LoadingState /> : visible.length === 0 ? <EmptyState title="No assignments found" description={query.data?.courses.length ? "Create an assignment or change the filters." : "Create a course before adding assignments."} href="/education/courses" action="Open courses" /> : <ul className="record-list">{visible.map((item) => { const overdue = Boolean(item.dueAt && item.dueAt < clock.now() && item.status !== "completed" && item.status !== "cancelled"); return <li className="record-card" key={item.id}><div><h3>{item.title}</h3><p>{courseName(item.courseId)} · {item.weightPercentage ? `${item.weightPercentage}%` : "No weight"}</p><p className={overdue ? "overdue" : undefined}>{item.dueAt ? `${overdue ? "Overdue · " : "Due "}${formatDateTime(item.dueAt)}` : "No due date"}</p></div><div className="record-actions"><StatusBadge value={item.status} />{(item.status === "draft" || item.status === "assigned") && <button className="button button-small button-secondary" disabled={action.pending} onClick={() => void action.execute(() => service.submitAssignment(context, item.id))}>Submit</button>}{item.status === "submitted" && <button className="button button-small button-primary" disabled={action.pending} onClick={() => void action.execute(() => service.markAssignmentComplete(context, item.id))}>Complete</button>}</div></li>; })}</ul>}
    </Panel></div>
  </>;
}

function AssignmentForm({ courses }: { readonly courses: readonly Course[] }) {
  const { service, context } = useEducation(); const action = useEducationAction();
  const [courseId, setCourseId] = useState(""); const [title, setTitle] = useState(""); const [dueAt, setDueAt] = useState(""); const [maximumScore, setMaximumScore] = useState(""); const [weight, setWeight] = useState(""); const [priority, setPriority] = useState<"low" | "normal" | "high" | "urgent">("normal");
  async function submit(event: FormEvent) { event.preventDefault(); const result = await action.execute(() => service.createAssignment(context, { courseId, title, ...(dueAt ? { dueAt: toIsoTimestamp(dueAt) } : {}), ...(maximumScore ? { maximumScore } : {}), ...(weight ? { weightPercentage: weight } : {}), priority, status: "assigned" })); if (result) { setTitle(""); setDueAt(""); setMaximumScore(""); setWeight(""); } }
  return <Panel title="Create assignment" description="Scores and weights stay as exact decimal strings."><form className="form-grid" onSubmit={submit} noValidate><div className="field-full"><SelectInput name="assignmentCourse" label="Course *" required value={courseId} onChange={(event) => setCourseId(event.target.value)} error={action.error?.fieldErrors.courseId}><option value="">Select course</option>{courses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectInput></div><div className="field-full"><TextInput name="assignmentTitle" label="Title *" required value={title} onChange={(event) => setTitle(event.target.value)} error={action.error?.fieldErrors.title} /></div><TextInput name="assignmentDue" label="Due date and time" type="datetime-local" value={dueAt} onChange={(event) => setDueAt(event.target.value)} error={action.error?.fieldErrors.dueAt} /><SelectInput name="assignmentPriority" label="Priority *" value={priority} onChange={(event) => setPriority(event.target.value as typeof priority)}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></SelectInput><TextInput name="assignmentMaximum" label="Maximum score" inputMode="decimal" value={maximumScore} onChange={(event) => setMaximumScore(event.target.value)} error={action.error?.fieldErrors.maximumScore} /><TextInput name="assignmentWeight" label="Weight (%)" inputMode="decimal" value={weight} onChange={(event) => setWeight(event.target.value)} error={action.error?.fieldErrors.weightPercentage} /><ErrorBanner error={action.error} /><div className="form-actions"><SubmitButton pending={action.pending}>Create assignment</SubmitButton></div></form></Panel>;
}
