"use client";

import { useCallback, useState, type FormEvent } from "react";
import type { AttendanceRecord, Course } from "@aperture/education";
import { useEducation } from "../providers/education-provider";
import { useEducationAction } from "../hooks/use-education-action";
import { useEducationQuery } from "../hooks/use-education-query";
import { EmptyState, ErrorBanner, LoadingState, PageHeader, Panel, SelectInput, StatusBadge, SubmitButton, TextInput, formatDate } from "../components/ui";

export function AttendanceScreen() {
  const { service, context } = useEducation(); const [courseId, setCourseId] = useState("");
  const load = useCallback(async () => (await service.listCourses(context)).items, [service, context]); const courses = useEducationQuery(load);
  return <><PageHeader eyebrow="Participation" title="Attendance" description="Record class attendance and view exact totals and percentages from the Education calculation service." /><div className="filters"><SelectInput name="attendanceCourseFilter" label="Course" value={courseId} onChange={(event) => setCourseId(event.target.value)}><option value="">Select a course</option>{courses.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectInput></div><ErrorBanner error={courses.error} />{courses.loading ? <LoadingState /> : !courseId ? <EmptyState title="Choose a course" description={courses.data?.length ? "Select a course to record and review attendance." : "Create a course before recording attendance."} href="/education/courses" action="Open courses" /> : <AttendanceWorkspace course={courses.data!.find((item) => item.id === courseId)!} />}</>;
}

function AttendanceWorkspace({ course }: { readonly course: Course }) {
  const { service, context } = useEducation(); const action = useEducationAction();
  const load = useCallback(async () => { const [records, summary] = await Promise.all([service.listAttendanceByCourse(context, { courseId: course.id }), service.getCourseAttendanceSummary(context, course.id, "exclude")]); return { records: records.items, summary }; }, [service, context, course.id]);
  const query = useEducationQuery(load);
  return <div className="grid grid-2"><AttendanceForm courseId={course.id} /><Panel title={`${course.name} attendance`} description="Excused records are excluded from the displayed percentage."><div className="grid metric-grid"><article className="metric"><span className="metric-label">Attendance</span><strong className="metric-value">{query.data?.summary.calculation.eligibleSessions ? `${query.data.summary.calculation.roundedAttendancePercentage}%` : "—"}</strong><span className="metric-detail">{query.data ? `${query.data.summary.calculation.attendedSessions} attended of ${query.data.summary.calculation.eligibleSessions} eligible` : "Loading totals"}</span></article><article className="metric"><span className="metric-label">Absent</span><strong className="metric-value">{query.data?.summary.calculation.absentSessions ?? 0}</strong><span className="metric-detail">Stored absence records</span></article></div><ErrorBanner error={query.error ?? action.error} />{query.loading ? <LoadingState /> : !query.data?.records.length ? <EmptyState title="No attendance records" description="Record a class session with the form." /> : <AttendanceList records={query.data.records} pending={action.pending} onDelete={(record) => { if (window.confirm(`Delete attendance for ${formatDate(record.sessionDate)}?`)) void action.execute(() => service.deleteAttendance(context, record.id)); }} />}</Panel></div>;
}

function AttendanceForm({ courseId }: { readonly courseId: string }) {
  const { service, context } = useEducation(); const action = useEducationAction(); const [sessionDate, setSessionDate] = useState(""); const [status, setStatus] = useState<"present" | "absent" | "late" | "excused" | "cancelled">("present"); const [scheduled, setScheduled] = useState(""); const [attended, setAttended] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); const result = await action.execute(() => service.recordAttendance(context, { courseId, sessionDate, status, source: "manual", ...(scheduled ? { scheduledDurationMinutes: Number(scheduled) } : {}), ...(attended ? { attendedDurationMinutes: Number(attended) } : {}) })); if (result) { setSessionDate(""); setScheduled(""); setAttended(""); } }
  return <Panel title="Record attendance" description="Use only the statuses defined by the Education domain."><form className="form-grid" onSubmit={submit} noValidate><TextInput name="attendanceDate" label="Session date *" type="date" required value={sessionDate} onChange={(event) => setSessionDate(event.target.value)} error={action.error?.fieldErrors.sessionDate} /><SelectInput name="attendanceStatus" label="Status *" value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option><option value="excused">Excused</option><option value="cancelled">Cancelled</option></SelectInput><TextInput name="attendanceScheduled" label="Scheduled minutes" type="number" min="0" value={scheduled} onChange={(event) => setScheduled(event.target.value)} error={action.error?.fieldErrors.scheduledDurationMinutes} /><TextInput name="attendanceAttended" label="Attended minutes" type="number" min="0" value={attended} onChange={(event) => setAttended(event.target.value)} error={action.error?.fieldErrors.attendedDurationMinutes} /><ErrorBanner error={action.error} /><div className="form-actions"><SubmitButton pending={action.pending}>Record attendance</SubmitButton></div></form></Panel>;
}

function AttendanceList({ records, pending, onDelete }: { readonly records: readonly AttendanceRecord[]; readonly pending: boolean; readonly onDelete: (record: AttendanceRecord) => void }) {
  return <ul className="record-list">{records.map((record) => <li className="record-card" key={record.id}><div><h3>{formatDate(record.sessionDate)}</h3><p>{record.attendedDurationMinutes ?? "—"} attended minutes · {record.source}</p></div><div className="record-actions"><StatusBadge value={record.status} /><button className="button button-small button-danger" disabled={pending} onClick={() => onDelete(record)}>Delete</button></div></li>)}</ul>;
}
