"use client";

import { useCallback, useMemo, useState, type FormEvent } from "react";
import type { Course, Exam } from "@aperture/education";
import { useEducation } from "../providers/education-provider";
import { useEducationAction } from "../hooks/use-education-action";
import { useEducationQuery } from "../hooks/use-education-query";
import { EmptyState, ErrorBanner, LoadingState, PageHeader, Panel, SelectInput, StatusBadge, SubmitButton, TextInput, formatDateTime, toIsoTimestamp } from "../components/ui";

interface ExamData { readonly courses: readonly Course[]; readonly exams: readonly Exam[]; }

export function ExamsScreen() {
  const { service, context } = useEducation(); const action = useEducationAction();
  const load = useCallback(async (): Promise<ExamData> => { const [courses, exams] = await Promise.all([service.listCourses(context), service.listExams(context)]); return { courses: courses.items, exams: exams.items }; }, [service, context]);
  const query = useEducationQuery(load); const [courseFilter, setCourseFilter] = useState(""); const [statusFilter, setStatusFilter] = useState("");
  const visible = useMemo(() => (query.data?.exams ?? []).filter((item) => (!courseFilter || item.courseId === courseFilter) && (!statusFilter || item.status === statusFilter)), [query.data, courseFilter, statusFilter]);
  const courseName = (id: string) => query.data?.courses.find((item) => item.id === id)?.name ?? "Unknown course";
  return <><PageHeader eyebrow="Assessments" title="Exams" description="Plan assessments and complete them through the existing Education lifecycle—without UI-owned countdowns or score logic." />
    <div className="grid grid-2"><ExamForm courses={query.data?.courses ?? []} /><Panel title="Exam schedule" description="Chronological assessment records with explicit status."><div className="filters"><SelectInput name="examCourseFilter" label="Course" value={courseFilter} onChange={(event) => setCourseFilter(event.target.value)}><option value="">All courses</option>{query.data?.courses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectInput><SelectInput name="examStatusFilter" label="Status" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="">All statuses</option><option value="scheduled">Scheduled</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></SelectInput></div><ErrorBanner error={query.error ?? action.error} />{query.loading ? <LoadingState /> : visible.length === 0 ? <EmptyState title="No exams found" description={query.data?.courses.length ? "Create an exam or change the filters." : "Create a course before scheduling exams."} href="/education/courses" action="Open courses" /> : <ul className="record-list">{visible.map((item) => <li className="record-card" key={item.id}><div><h3>{item.title}</h3><p>{courseName(item.courseId)} · {item.examType}</p><p>{formatDateTime(item.scheduledStartsAt)} → {formatDateTime(item.scheduledEndsAt)}</p><p>{item.maximumScore ? `${item.maximumScore} maximum marks` : "Maximum not set"}{item.weightPercentage ? ` · ${item.weightPercentage}% weight` : ""}</p></div><div className="record-actions"><StatusBadge value={item.status} />{item.status === "scheduled" && <button className="button button-small button-primary" disabled={action.pending} onClick={() => void action.execute(() => service.completeExam(context, item.id))}>Complete</button>}</div></li>)}</ul>}</Panel></div>
  </>;
}

function ExamForm({ courses }: { readonly courses: readonly Course[] }) {
  const { service, context } = useEducation(); const action = useEducationAction();
  const [courseId, setCourseId] = useState(""); const [title, setTitle] = useState(""); const [examType, setExamType] = useState<"quiz" | "midterm" | "final" | "practical" | "oral" | "other">("quiz"); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [maximumScore, setMaximumScore] = useState(""); const [weight, setWeight] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); const result = await action.execute(() => service.createExam(context, { courseId, title, examType, scheduledStartsAt: toIsoTimestamp(start), scheduledEndsAt: toIsoTimestamp(end), ...(maximumScore ? { maximumScore } : {}), ...(weight ? { weightPercentage: weight } : {}), status: "scheduled" })); if (result) { setTitle(""); setStart(""); setEnd(""); setMaximumScore(""); setWeight(""); } }
  return <Panel title="Schedule exam" description="End time must not precede the start."><form className="form-grid" onSubmit={submit} noValidate><div className="field-full"><SelectInput name="examCourse" label="Course *" required value={courseId} onChange={(event) => setCourseId(event.target.value)} error={action.error?.fieldErrors.courseId}><option value="">Select course</option>{courses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectInput></div><div className="field-full"><TextInput name="examTitle" label="Exam name *" required value={title} onChange={(event) => setTitle(event.target.value)} error={action.error?.fieldErrors.title} /></div><SelectInput name="examType" label="Exam type *" value={examType} onChange={(event) => setExamType(event.target.value as typeof examType)}><option value="quiz">Quiz</option><option value="midterm">Midterm</option><option value="final">Final</option><option value="practical">Practical</option><option value="oral">Oral</option><option value="other">Other</option></SelectInput><span /><TextInput name="examStart" label="Starts *" type="datetime-local" required value={start} onChange={(event) => setStart(event.target.value)} error={action.error?.fieldErrors.scheduledStartsAt} /><TextInput name="examEnd" label="Ends *" type="datetime-local" required value={end} onChange={(event) => setEnd(event.target.value)} error={action.error?.fieldErrors.scheduledEndsAt} /><TextInput name="examMaximum" label="Maximum marks" inputMode="decimal" value={maximumScore} onChange={(event) => setMaximumScore(event.target.value)} error={action.error?.fieldErrors.maximumScore} /><TextInput name="examWeight" label="Weight (%)" inputMode="decimal" value={weight} onChange={(event) => setWeight(event.target.value)} error={action.error?.fieldErrors.weightPercentage} /><ErrorBanner error={action.error} /><div className="form-actions"><SubmitButton pending={action.pending}>Schedule exam</SubmitButton></div></form></Panel>;
}
