"use client";

import { useCallback, useState, type FormEvent } from "react";
import type { Course, StudySession } from "@aperture/education";
import { useEducation } from "../providers/education-provider";
import { useEducationAction } from "../hooks/use-education-action";
import { useEducationQuery } from "../hooks/use-education-query";
import { EmptyState, ErrorBanner, LoadingState, PageHeader, Panel, SelectInput, StatusBadge, SubmitButton, TextInput, formatDateTime, toIsoTimestamp } from "../components/ui";

export function StudySessionsScreen() {
  const { service, context } = useEducation(); const [courseId, setCourseId] = useState("");
  const load = useCallback(async () => (await service.listCourses(context)).items, [service, context]); const courses = useEducationQuery(load);
  return <><PageHeader eyebrow="Focused work" title="Study sessions" description="Schedule focused work and move it through explicit start, complete, or cancel transitions using the injected service clock." /><div className="filters"><SelectInput name="studyCourseFilter" label="Course" value={courseId} onChange={(event) => setCourseId(event.target.value)}><option value="">Select a course</option>{courses.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectInput></div><ErrorBanner error={courses.error} />{courses.loading ? <LoadingState /> : !courseId ? <EmptyState title="Choose a course" description={courses.data?.length ? "Select a course to plan and review study sessions." : "Create a course before scheduling study."} href="/education/courses" action="Open courses" /> : <StudyWorkspace course={courses.data!.find((item) => item.id === courseId)!} />}</>;
}

function StudyWorkspace({ course }: { readonly course: Course }) {
  const { service, context, clock } = useEducation(); const action = useEducationAction();
  const load = useCallback(async () => { const now = clock.now(); const year = now.slice(0, 4); const [sessions, summary] = await Promise.all([service.listStudySessionsByCourse(context, { courseId: course.id }), service.getStudyTimeSummary(context, { courseId: course.id, range: { startsOn: `${year}-01-01`, endsOn: `${year}-12-31` } })]); return { sessions: sessions.items, summary }; }, [service, context, clock, course.id]);
  const query = useEducationQuery(load);
  return <div className="grid grid-2"><StudyForm courseId={course.id} /><Panel title={`${course.name} study`} description="Only stored actual durations contribute to the service summary."><div className="grid metric-grid"><article className="metric"><span className="metric-label">Completed study</span><strong className="metric-value">{query.data?.summary.totalMinutes ?? 0} min</strong><span className="metric-detail">{query.data?.summary.sessionCount ?? 0} sessions · {query.data?.summary.omittedSessionCount ?? 0} missing duration</span></article></div><ErrorBanner error={query.error ?? action.error} />{query.loading ? <LoadingState /> : !query.data?.sessions.length ? <EmptyState title="No study sessions" description="Schedule focused work with the form." /> : <StudyList sessions={query.data.sessions} pending={action.pending} onStart={(item) => void action.execute(() => service.startStudySession(context, item.id))} onComplete={(item) => void action.execute(() => service.completeStudySession(context, item.id))} onCancel={(item) => { if (window.confirm(`Cancel ${item.title}?`)) void action.execute(() => service.cancelStudySession(context, item.id)); }} />}</Panel></div>;
}

function StudyForm({ courseId }: { readonly courseId: string }) {
  const { service, context } = useEducation(); const action = useEducationAction(); const [title, setTitle] = useState(""); const [startsAt, setStartsAt] = useState(""); const [endsAt, setEndsAt] = useState(""); const [minutes, setMinutes] = useState(""); const [method, setMethod] = useState<"reading" | "practice" | "review" | "lecture" | "group" | "other">("reading");
  async function submit(event: FormEvent) { event.preventDefault(); const result = await action.execute(() => service.scheduleStudySession(context, { courseId, title, plannedStartsAt: toIsoTimestamp(startsAt), ...(endsAt ? { plannedEndsAt: toIsoTimestamp(endsAt) } : {}), ...(minutes ? { plannedDurationMinutes: Number(minutes) } : {}), method, status: "scheduled" })); if (result) { setTitle(""); setStartsAt(""); setEndsAt(""); setMinutes(""); } }
  return <Panel title="Schedule study" description="The service supplies actual start and completion timestamps."><form className="form-grid" onSubmit={submit} noValidate><div className="field-full"><TextInput name="studyTitle" label="Session title *" required value={title} onChange={(event) => setTitle(event.target.value)} error={action.error?.fieldErrors.title} /></div><TextInput name="studyStart" label="Planned start *" type="datetime-local" required value={startsAt} onChange={(event) => setStartsAt(event.target.value)} error={action.error?.fieldErrors.plannedStartsAt} /><TextInput name="studyEnd" label="Planned end" type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} error={action.error?.fieldErrors.plannedEndsAt} /><TextInput name="studyMinutes" label="Planned minutes" type="number" min="0" value={minutes} onChange={(event) => setMinutes(event.target.value)} error={action.error?.fieldErrors.plannedDurationMinutes} /><SelectInput name="studyMethod" label="Study method *" value={method} onChange={(event) => setMethod(event.target.value as typeof method)}><option value="reading">Reading</option><option value="practice">Practice</option><option value="review">Review</option><option value="lecture">Lecture</option><option value="group">Group</option><option value="other">Other</option></SelectInput><ErrorBanner error={action.error} /><div className="form-actions"><SubmitButton pending={action.pending}>Schedule session</SubmitButton></div></form></Panel>;
}

function StudyList({ sessions, pending, onStart, onComplete, onCancel }: { readonly sessions: readonly StudySession[]; readonly pending: boolean; readonly onStart: (item: StudySession) => void; readonly onComplete: (item: StudySession) => void; readonly onCancel: (item: StudySession) => void }) {
  return <ul className="record-list">{sessions.map((item) => <li className="record-card" key={item.id}><div><h3>{item.title}</h3><p>{formatDateTime(item.plannedStartsAt)} · {item.method}</p><p>{item.plannedDurationMinutes ?? "—"} planned minutes{item.actualDurationMinutes !== undefined ? ` · ${item.actualDurationMinutes} actual` : ""}</p></div><div className="record-actions"><StatusBadge value={item.status} />{item.status === "scheduled" && <button className="button button-small button-secondary" disabled={pending} onClick={() => onStart(item)}>Start</button>}{(item.status === "in_progress" || item.status === "paused") && <button className="button button-small button-primary" disabled={pending} onClick={() => onComplete(item)}>Complete</button>}{item.status !== "completed" && item.status !== "cancelled" && <button className="button button-small button-danger" disabled={pending} onClick={() => onCancel(item)}>Cancel</button>}</div></li>)}</ul>;
}
