/* Generated by tooling/plugins/generate-plugins.mjs. Do not edit directly. */
import type { FeatureManifest } from "./feature-manifest.js";

export const generatedFeatureManifests = [
  {
    "schemaVersion": 1,
    "id": "today",
    "displayName": "Today",
    "description": "Your daily plan, deadlines, reminders, and quick actions in one place.",
    "version": "0.1.0",
    "status": "enabled",
    "defaultEnabled": true,
    "disableAllowed": false,
    "order": 10,
    "icon": "sun",
    "theme": {
      "accent": "#d88921",
      "surface": "#fff4dc"
    },
    "permissions": [
      {
        "id": "today.read",
        "description": "Read enabled dashboard contributions.",
        "required": true
      }
    ],
    "routes": [
      {
        "id": "today.overview",
        "label": "Today",
        "description": "Open the daily dashboard.",
        "paths": {
          "web": "/today",
          "mobile": "/today"
        },
        "navigation": "primary",
        "order": 10,
        "searchable": true,
        "requiresSession": true
      }
    ],
    "widgets": [],
    "calculatorModules": [],
    "frontends": {
      "web": {
        "source": "apps/web/src/features/today/index.ts",
        "import": "../features/today/index"
      },
      "mobile": {
        "source": "apps/mobile/src/features/today/index.ts",
        "import": "../features/today/index"
      }
    },
    "migrations": []
  },
  {
    "schemaVersion": 1,
    "id": "education",
    "displayName": "Education",
    "description": "Plan courses, assessments, attendance, grades, and study sessions.",
    "version": "0.8.0",
    "status": "enabled",
    "defaultEnabled": true,
    "disableAllowed": true,
    "order": 20,
    "icon": "book",
    "theme": {
      "accent": "#087f72",
      "surface": "#dff4ee"
    },
    "permissions": [
      {
        "id": "education.read",
        "description": "Read owner-scoped education records.",
        "required": true
      },
      {
        "id": "education.write",
        "description": "Create and update owner-scoped education records.",
        "required": true
      }
    ],
    "routes": [
      {
        "id": "education.overview",
        "label": "Overview",
        "description": "Review academic progress and next actions.",
        "paths": {
          "web": "/education",
          "mobile": "/education"
        },
        "navigation": "primary",
        "order": 20,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "education.setup",
        "label": "Academic setup",
        "description": "Manage institution, program, and semester details.",
        "paths": {
          "web": "/education/setup",
          "mobile": "/education/setup"
        },
        "navigation": "secondary",
        "order": 21,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "education.courses",
        "label": "Courses",
        "description": "Open the course directory.",
        "paths": {
          "web": "/education/courses",
          "mobile": "/education/courses"
        },
        "navigation": "secondary",
        "order": 22,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "education.assignments",
        "label": "Assignments",
        "description": "Track deadlines and submissions.",
        "paths": {
          "web": "/education/assignments",
          "mobile": "/education/assignments"
        },
        "navigation": "secondary",
        "order": 23,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "education.exams",
        "label": "Exams",
        "description": "Review the assessment schedule.",
        "paths": {
          "web": "/education/exams",
          "mobile": "/education/exams"
        },
        "navigation": "secondary",
        "order": 24,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "education.grades",
        "label": "Grades",
        "description": "Review scores, GPA, and CGPA.",
        "paths": {
          "web": "/education/grades",
          "mobile": "/education/grades"
        },
        "navigation": "secondary",
        "order": 25,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "education.attendance",
        "label": "Attendance",
        "description": "Review attendance records and totals.",
        "paths": {
          "web": "/education/attendance",
          "mobile": "/education/attendance"
        },
        "navigation": "secondary",
        "order": 26,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "education.study",
        "label": "Study sessions",
        "description": "Plan and complete focused study.",
        "paths": {
          "web": "/education/study-sessions",
          "mobile": "/education/study-sessions"
        },
        "navigation": "secondary",
        "order": 27,
        "searchable": true,
        "requiresSession": true
      }
    ],
    "widgets": [
      {
        "id": "education.deadlines",
        "title": "Education deadlines",
        "description": "Upcoming assignments and exams.",
        "platforms": [
          "web",
          "mobile"
        ],
        "order": 20,
        "defaultEnabled": true
      },
      {
        "id": "education.study",
        "title": "Planned study",
        "description": "Study sessions scheduled for this date.",
        "platforms": [
          "web",
          "mobile"
        ],
        "order": 21,
        "defaultEnabled": true
      }
    ],
    "calculatorModules": [
      {
        "id": "education.academic",
        "source": "packages/education/src/index.ts",
        "import": "@aperture/education"
      }
    ],
    "frontends": {
      "web": {
        "source": "apps/web/src/features/education/index.ts",
        "import": "../features/education/index"
      },
      "mobile": {
        "source": "apps/mobile/src/features/education/index.ts",
        "import": "../features/education/index"
      }
    },
    "backend": {
      "source": "packages/education/src/index.ts",
      "import": "@aperture/education"
    },
    "migrations": [
      "packages/education/migrations/20260921001000_education.sql"
    ]
  },
  {
    "schemaVersion": 1,
    "id": "health",
    "displayName": "Health",
    "description": "Keep private wellness, activity, nutrition, sleep, and measurement records.",
    "version": "0.5.0",
    "status": "enabled",
    "defaultEnabled": true,
    "disableAllowed": true,
    "order": 30,
    "icon": "heart",
    "theme": {
      "accent": "#0b766c",
      "surface": "#daf4ee"
    },
    "permissions": [
      {
        "id": "health.read",
        "description": "Read owner-scoped health records.",
        "required": true
      },
      {
        "id": "health.write",
        "description": "Create and update owner-scoped health records.",
        "required": true
      }
    ],
    "routes": [
      {
        "id": "health.overview",
        "label": "Overview",
        "description": "Review wellness records and next actions.",
        "paths": {
          "web": "/health",
          "mobile": "/health"
        },
        "navigation": "primary",
        "order": 30,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "health.profile",
        "label": "Profile",
        "description": "Manage measurement preferences and profile details.",
        "paths": {
          "web": "/health/profile",
          "mobile": "/health/profile"
        },
        "navigation": "secondary",
        "order": 31,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "health.measurements",
        "label": "Measurements",
        "description": "Review body measurement history.",
        "paths": {
          "web": "/health/measurements",
          "mobile": "/health/measurements"
        },
        "navigation": "secondary",
        "order": 32,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "health.vitals",
        "label": "Vitals",
        "description": "Review recorded vital observations.",
        "paths": {
          "web": "/health/vitals",
          "mobile": "/health/vitals"
        },
        "navigation": "secondary",
        "order": 33,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "health.workouts",
        "label": "Workouts",
        "description": "Manage exercises, plans, sessions, and sets.",
        "paths": {
          "web": "/health/workouts",
          "mobile": "/health/workouts"
        },
        "navigation": "secondary",
        "order": 34,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "health.running",
        "label": "Running",
        "description": "Review routes, equipment, activities, and results.",
        "paths": {
          "web": "/health/running",
          "mobile": "/health/running"
        },
        "navigation": "secondary",
        "order": 35,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "health.sleep",
        "label": "Sleep",
        "description": "Review sleep timing and personal quality.",
        "paths": {
          "web": "/health/sleep",
          "mobile": "/health/sleep"
        },
        "navigation": "secondary",
        "order": 36,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "health.nutrition",
        "label": "Nutrition",
        "description": "Review meal and energy records.",
        "paths": {
          "web": "/health/nutrition",
          "mobile": "/health/nutrition"
        },
        "navigation": "secondary",
        "order": 37,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "health.hydration",
        "label": "Hydration",
        "description": "Review consumed volume records.",
        "paths": {
          "web": "/health/hydration",
          "mobile": "/health/hydration"
        },
        "navigation": "secondary",
        "order": 38,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "health.goals",
        "label": "Progress",
        "description": "Review goals, achievements, and recovery observations.",
        "paths": {
          "web": "/health/goals",
          "mobile": "/health/goals"
        },
        "navigation": "secondary",
        "order": 39,
        "searchable": true,
        "requiresSession": true
      }
    ],
    "widgets": [
      {
        "id": "health.plans",
        "title": "Health plans",
        "description": "Planned workouts and wellness actions.",
        "platforms": [
          "web",
          "mobile"
        ],
        "order": 30,
        "defaultEnabled": true
      }
    ],
    "calculatorModules": [],
    "frontends": {
      "web": {
        "source": "apps/web/src/features/health/index.ts",
        "import": "../features/health/index"
      },
      "mobile": {
        "source": "apps/mobile/src/features/health/index.ts",
        "import": "../features/health/index"
      }
    },
    "backend": {
      "source": "packages/health/src/index.ts",
      "import": "@aperture/health"
    },
    "migrations": [
      "packages/health/migrations/20260921002000_health.sql"
    ]
  },
  {
    "schemaVersion": 1,
    "id": "finance",
    "displayName": "Finance",
    "description": "Track personal accounts, cash flow, assets, liabilities, budgets, and goals.",
    "version": "0.5.0",
    "status": "enabled",
    "defaultEnabled": true,
    "disableAllowed": true,
    "order": 40,
    "icon": "wallet",
    "theme": {
      "accent": "#6658a6",
      "surface": "#e6e0f7"
    },
    "permissions": [
      {
        "id": "finance.read",
        "description": "Read owner-scoped finance records.",
        "required": true
      },
      {
        "id": "finance.write",
        "description": "Create and update owner-scoped finance records.",
        "required": true
      }
    ],
    "routes": [
      {
        "id": "finance.overview",
        "label": "Overview",
        "description": "Review balances, budgets, and financial goals.",
        "paths": {
          "web": "/finance",
          "mobile": "/finance"
        },
        "navigation": "primary",
        "order": 40,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "finance.accounts",
        "label": "Accounts",
        "description": "Manage personal account records.",
        "paths": {
          "web": "/finance/accounts",
          "mobile": "/finance/accounts"
        },
        "navigation": "secondary",
        "order": 41,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "finance.transactions",
        "label": "Transactions",
        "description": "Review income and expense records.",
        "paths": {
          "web": "/finance/transactions",
          "mobile": "/finance/transactions"
        },
        "navigation": "secondary",
        "order": 42,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "finance.budgets",
        "label": "Budgets",
        "description": "Plan spending limits and periods.",
        "paths": {
          "web": "/finance/budgets",
          "mobile": "/finance/budgets"
        },
        "navigation": "secondary",
        "order": 43,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "finance.assets",
        "label": "Assets",
        "description": "Review owned assets and valuations.",
        "paths": {
          "web": "/finance/assets",
          "mobile": "/finance/assets"
        },
        "navigation": "secondary",
        "order": 44,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "finance.liabilities",
        "label": "Liabilities",
        "description": "Review liabilities and balances.",
        "paths": {
          "web": "/finance/liabilities",
          "mobile": "/finance/liabilities"
        },
        "navigation": "secondary",
        "order": 45,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "finance.investments",
        "label": "Investments",
        "description": "Review investment positions.",
        "paths": {
          "web": "/finance/investments",
          "mobile": "/finance/investments"
        },
        "navigation": "secondary",
        "order": 46,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "finance.loans",
        "label": "Loans",
        "description": "Review loan records and payments.",
        "paths": {
          "web": "/finance/loans",
          "mobile": "/finance/loans"
        },
        "navigation": "secondary",
        "order": 47,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "finance.goals",
        "label": "Goals",
        "description": "Review financial targets and progress.",
        "paths": {
          "web": "/finance/goals",
          "mobile": "/finance/goals"
        },
        "navigation": "secondary",
        "order": 48,
        "searchable": true,
        "requiresSession": true
      }
    ],
    "widgets": [
      {
        "id": "finance.reminders",
        "title": "Finance reminders",
        "description": "Budget, payment, and goal reminders.",
        "platforms": [
          "web",
          "mobile"
        ],
        "order": 40,
        "defaultEnabled": true
      }
    ],
    "calculatorModules": [],
    "frontends": {
      "web": {
        "source": "apps/web/src/features/finance/index.ts",
        "import": "../features/finance/index"
      },
      "mobile": {
        "source": "apps/mobile/src/features/finance/index.ts",
        "import": "../features/finance/index"
      }
    },
    "backend": {
      "source": "packages/finance/src/runtime.ts",
      "import": "@aperture/finance"
    },
    "migrations": [
      "packages/finance/migrations/20260921003000_finance.sql"
    ]
  },
  {
    "schemaVersion": 1,
    "id": "planner",
    "displayName": "Planner",
    "description": "Plan tasks, events, reminders, focus blocks, and recurring work.",
    "version": "0.1.0",
    "status": "enabled",
    "defaultEnabled": true,
    "disableAllowed": true,
    "order": 45,
    "icon": "calendar",
    "theme": {
      "accent": "#38628e",
      "surface": "#e8eef7"
    },
    "permissions": [
      {
        "id": "planner.read",
        "description": "Read owner-scoped plans and items.",
        "required": true
      },
      {
        "id": "planner.write",
        "description": "Create and update owner-scoped plans and items.",
        "required": true
      }
    ],
    "routes": [
      {
        "id": "planner.day",
        "label": "Daily plan",
        "description": "Plan and complete work for one day.",
        "paths": {
          "web": "/planner",
          "mobile": "/planner"
        },
        "navigation": "primary",
        "order": 45,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "planner.week",
        "label": "Weekly plan",
        "description": "Review recurring and scheduled work across a week.",
        "paths": {
          "web": "/planner/week",
          "mobile": "/planner/week"
        },
        "navigation": "secondary",
        "order": 46,
        "searchable": true,
        "requiresSession": true
      }
    ],
    "widgets": [
      {
        "id": "planner.items",
        "title": "Planner tasks",
        "description": "Scheduled and overdue planner items.",
        "platforms": [
          "web",
          "mobile"
        ],
        "order": 10,
        "defaultEnabled": true
      }
    ],
    "calculatorModules": [],
    "frontends": {
      "web": {
        "source": "apps/web/src/features/planner/index.ts",
        "import": "../features/planner/index"
      },
      "mobile": {
        "source": "apps/mobile/src/features/planner/index.ts",
        "import": "../features/planner/index"
      }
    },
    "backend": {
      "source": "packages/planner/src/index.ts",
      "import": "@aperture/planner"
    },
    "migrations": [
      "packages/planner/migrations/20260922001000_planner.sql"
    ]
  },
  {
    "schemaVersion": 1,
    "id": "calculators",
    "displayName": "Calculators",
    "description": "Run the shared academic and finance calculator catalog.",
    "version": "0.5.0",
    "status": "enabled",
    "defaultEnabled": true,
    "disableAllowed": true,
    "order": 50,
    "icon": "calculator",
    "theme": {
      "accent": "#51448b",
      "surface": "#f2effa"
    },
    "permissions": [
      {
        "id": "calculators.use",
        "description": "Run local deterministic calculators.",
        "required": true
      }
    ],
    "routes": [
      {
        "id": "calculators.catalog",
        "label": "Calculators",
        "description": "Search and run the calculator catalog.",
        "paths": {
          "web": "/calculators",
          "mobile": "/calculators"
        },
        "navigation": "primary",
        "order": 50,
        "searchable": true,
        "requiresSession": true
      },
      {
        "id": "calculators.detail",
        "label": "Calculator",
        "description": "Run a selected calculator.",
        "paths": {
          "web": "/calculators/[calculator-id]",
          "mobile": "/calculators/[calculator-id]"
        },
        "navigation": "hidden",
        "order": 51,
        "searchable": false,
        "requiresSession": true
      }
    ],
    "widgets": [],
    "calculatorModules": [
      {
        "id": "calculators.shared",
        "source": "packages/calculators/src/runtime.ts",
        "import": "@aperture/calculators"
      }
    ],
    "frontends": {
      "web": {
        "source": "apps/web/src/features/finance/index.ts",
        "import": "../features/finance/index"
      },
      "mobile": {
        "source": "apps/mobile/src/features/finance/index.ts",
        "import": "../features/finance/index"
      }
    },
    "backend": {
      "source": "packages/calculators/src/runtime.ts",
      "import": "@aperture/calculators"
    },
    "migrations": []
  },
  {
    "schemaVersion": 1,
    "id": "settings",
    "displayName": "Settings",
    "description": "Control the dashboard experience, privacy, and enabled features.",
    "version": "0.1.0",
    "status": "enabled",
    "defaultEnabled": true,
    "disableAllowed": false,
    "order": 60,
    "icon": "settings",
    "theme": {
      "accent": "#4d6470",
      "surface": "#e7eef1"
    },
    "permissions": [
      {
        "id": "settings.read",
        "description": "Read personal dashboard settings.",
        "required": true
      }
    ],
    "routes": [
      {
        "id": "settings.overview",
        "label": "Settings",
        "description": "Open dashboard settings and privacy controls.",
        "paths": {
          "web": "/settings",
          "mobile": "/settings"
        },
        "navigation": "primary",
        "order": 60,
        "searchable": true,
        "requiresSession": true
      }
    ],
    "widgets": [],
    "calculatorModules": [],
    "frontends": {
      "web": {
        "source": "apps/web/src/features/settings/index.ts",
        "import": "../features/settings/index"
      },
      "mobile": {
        "source": "apps/mobile/src/features/settings/index.ts",
        "import": "../features/settings/index"
      }
    },
    "migrations": [
      "packages/platform-contracts/migrations/20260921004000_platform.sql"
    ]
  }
] as const satisfies readonly FeatureManifest[];
