import { useCallback, useState } from "react";
import type { AssetType } from "@aperture/finance";
import { ActionButton, ChoiceField, EmptyState, ErrorBanner, LoadingState, PageHeader, Panel, RecordCard, RecordList, Screen, TextField, formatMoney } from "../components/ui";
import { useFinanceAction } from "../hooks/use-finance-action"; import { useFinanceQuery } from "../hooks/use-finance-query"; import { useFinance } from "../providers/finance-provider";

const assetTypes: readonly AssetType[] = ["cash", "property", "vehicle", "investment", "retirement", "other"];
export function AssetsScreen() {
  const { service, context } = useFinance(); const action = useFinanceAction(); const [name, setName] = useState(""); const [assetType, setAssetType] = useState<AssetType>("cash"); const [amount, setAmount] = useState(""); const [currency, setCurrency] = useState("USD"); const [valuedOn, setValuedOn] = useState(new Date().toISOString().slice(0, 10));
  const load = useCallback(() => service.assets.list(context), [service, context]); const query = useFinanceQuery(load);
  const submit = () => void action.execute(() => service.assets.create(context, { name, assetType, currentValue: { amount, currency }, valuedOn })).then((result) => { if (result) { setName(""); setAmount(""); } });
  return <Screen testID="finance-assets-screen"><PageHeader eyebrow="Balance sheet" title="Assets" description="Record the value and valuation date of assets without assuming market prices or converting currencies." /><ErrorBanner error={query.error ?? action.error} /><Panel title="Add asset"><TextField label="Asset name" name="asset-name" value={name} onChangeText={setName} required /><ChoiceField label="Asset type" value={assetType} onChange={setAssetType} options={assetTypes.map((value) => ({ value, label: value }))} /><TextField label="Current value" name="asset-value" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" required /><TextField label="Currency" name="asset-currency" value={currency} onChangeText={(value) => setCurrency(value.toUpperCase())} autoCapitalize="characters" required /><TextField label="Valued on" name="asset-date" value={valuedOn} onChangeText={setValuedOn} hint="Use YYYY-MM-DD." required /><ActionButton label="Add asset" pending={action.pending} onPress={submit} /></Panel><Panel title="Recorded assets">{query.loading || !query.data ? <LoadingState /> : query.data.items.length === 0 ? <EmptyState title="No assets" description="Add a manually valued asset above." /> : <RecordList items={query.data.items} keyExtractor={(item) => item.id} accessibilityLabel="Recorded assets" renderItem={(item) => <RecordCard title={item.name} status={item.status} details={[`${formatMoney(item.currentValue)} · valued ${item.valuedOn}`]}>{item.status === "active" ? <ActionButton label="Archive" tone="danger" onPress={() => void action.execute(() => service.assets.archive(context, item.id))} /> : null}</RecordCard>} />}</Panel></Screen>;
}
