import { useCallback, useState } from "react";
import { ActionButton, EmptyState, ErrorBanner, LoadingState, PageHeader, Panel, RecordCard, RecordList, Screen, TextField, formatMoney } from "../components/ui";
import { useFinanceAction } from "../hooks/use-finance-action"; import { useFinanceQuery } from "../hooks/use-finance-query"; import { useFinance } from "../providers/finance-provider";

export function GoalsScreen() {
  const { service, context } = useFinance(); const action = useFinanceAction(); const [name, setName] = useState(""); const [target, setTarget] = useState(""); const [progress, setProgress] = useState("0"); const [currency, setCurrency] = useState("USD"); const [targetDate, setTargetDate] = useState(new Date().toISOString().slice(0, 10));
  const load = useCallback(() => service.goals.list(context), [service, context]); const query = useFinanceQuery(load);
  const submit = () => void action.execute(() => service.goals.create(context, { name, targetAmount: { amount: target, currency }, recordedProgressAmount: { amount: progress || "0", currency }, targetDate })).then((result) => { if (result) { setName(""); setTarget(""); setProgress("0"); } });
  return <Screen testID="finance-goals-screen"><PageHeader eyebrow="Personal planning" title="Financial goals" description="Record a target and manually updated progress without recommendations or automated transfers." /><ErrorBanner error={query.error ?? action.error} /><Panel title="Add goal"><TextField label="Goal name" name="goal-name" value={name} onChangeText={setName} required /><TextField label="Target amount" name="goal-target" value={target} onChangeText={setTarget} keyboardType="decimal-pad" required /><TextField label="Recorded progress" name="goal-progress" value={progress} onChangeText={setProgress} keyboardType="decimal-pad" /><TextField label="Currency" name="goal-currency" value={currency} onChangeText={(value) => setCurrency(value.toUpperCase())} autoCapitalize="characters" required /><TextField label="Target date" name="goal-date" value={targetDate} onChangeText={setTargetDate} hint="Use YYYY-MM-DD." required /><ActionButton label="Add goal" pending={action.pending} onPress={submit} /></Panel><Panel title="Goal progress">{query.loading || !query.data ? <LoadingState /> : query.data.items.length === 0 ? <EmptyState title="No goals" description="Add a target above." /> : <RecordList items={query.data.items} keyExtractor={(item) => item.id} accessibilityLabel="Financial goals" renderItem={(item) => <RecordCard title={item.name} status={item.status} details={[`${formatMoney(item.recordedProgressAmount ?? { amount: "0", currency: item.targetAmount.currency })} of ${formatMoney(item.targetAmount)}`, `Due ${item.targetDate}`]}>{item.status === "active" ? <ActionButton label="Complete" tone="secondary" onPress={() => void action.execute(() => service.goals.complete(context, item.id))} /> : null}<ActionButton label="Archive" tone="danger" onPress={() => void action.execute(() => service.goals.archive(context, item.id))} /></RecordCard>} />}</Panel></Screen>;
}
