import { useCallback, useState } from "react";
import { ActionButton, ChoiceField, EmptyState, ErrorBanner, LoadingState, PageHeader, Panel, RecordCard, RecordList, Screen, TextField } from "../components/ui";
import { useFinanceAction } from "../hooks/use-finance-action"; import { useFinanceQuery } from "../hooks/use-finance-query"; import { useFinance } from "../providers/finance-provider";

export function InvestmentsScreen() {
  const { service, context } = useFinance(); const action = useFinanceAction(); const [accountName, setAccountName] = useState(""); const [accountCurrency, setAccountCurrency] = useState("USD"); const [financialAccountId, setFinancialAccountId] = useState(""); const [name, setName] = useState("");
  const load = useCallback(async () => { const [accounts, investments] = await Promise.all([service.accounts.list(context), service.investmentAccounts.list(context)]); return { accounts: accounts.items.filter(({ accountType }) => accountType === "investment" || accountType === "retirement"), investments: investments.items }; }, [service, context]); const query = useFinanceQuery(load);
  const addAccount = () => void action.execute(() => service.accounts.create(context, { name: accountName, accountType: "investment", currency: accountCurrency })).then((result) => { if (result) setAccountName(""); });
  const addInvestment = () => { const account = query.data?.accounts.find((item) => item.id === financialAccountId); void action.execute(() => service.investmentAccounts.create(context, { financialAccountId, name, currency: account?.currency ?? accountCurrency })).then((result) => { if (result) setName(""); }); };
  return <Screen testID="finance-investments-screen"><PageHeader eyebrow="Investment records" title="Investments" description="Create manual investment account records. Holdings and market feeds arrive in later infrastructure work." /><ErrorBanner error={query.error ?? action.error} /><Panel title="Add investment financial account"><TextField label="Account name" name="investment-financial-name" value={accountName} onChangeText={setAccountName} required /><TextField label="Currency" name="investment-financial-currency" value={accountCurrency} onChangeText={(value) => setAccountCurrency(value.toUpperCase())} autoCapitalize="characters" required /><ActionButton label="Add financial account" pending={action.pending} onPress={addAccount} /></Panel><Panel title="Add investment account"><ChoiceField label="Linked financial account" value={financialAccountId} onChange={setFinancialAccountId} options={(query.data?.accounts ?? []).map((item) => ({ value: item.id, label: item.name }))} required /><TextField label="Investment account name" name="investment-name" value={name} onChangeText={setName} required /><ActionButton label="Add investment account" pending={action.pending} disabled={!financialAccountId} onPress={addInvestment} /></Panel><Panel title="Investment accounts">{query.loading || !query.data ? <LoadingState /> : query.data.investments.length === 0 ? <EmptyState title="No investment accounts" description="Create a linked financial account and investment record above." /> : <RecordList items={query.data.investments} keyExtractor={(item) => item.id} accessibilityLabel="Investment accounts" renderItem={(item) => <RecordCard title={item.name} status={item.status} details={[`${item.currency} · linked account ${item.financialAccountId}`]}>{item.status === "active" ? <ActionButton label="Archive" tone="danger" onPress={() => void action.execute(() => service.investmentAccounts.archive(context, item.id))} /> : null}</RecordCard>} />}</Panel></Screen>;
}
