import { useCallback, useState } from "react";
import type { LiabilityType } from "@aperture/finance";
import { ActionButton, ChoiceField, EmptyState, ErrorBanner, LoadingState, PageHeader, Panel, RecordCard, RecordList, Screen, TextField, formatMoney } from "../components/ui";
import { useFinanceAction } from "../hooks/use-finance-action"; import { useFinanceQuery } from "../hooks/use-finance-query"; import { useFinance } from "../providers/finance-provider";

const liabilityTypes: readonly LiabilityType[] = ["mortgage", "personal_loan", "auto_loan", "credit_card", "tax", "other"];
export function LiabilitiesScreen() {
  const { service, context } = useFinance(); const action = useFinanceAction(); const [name, setName] = useState(""); const [liabilityType, setLiabilityType] = useState<LiabilityType>("mortgage"); const [amount, setAmount] = useState(""); const [currency, setCurrency] = useState("USD"); const [valuedOn, setValuedOn] = useState(new Date().toISOString().slice(0, 10));
  const load = useCallback(() => service.liabilities.list(context), [service, context]); const query = useFinanceQuery(load);
  const submit = () => void action.execute(() => service.liabilities.create(context, { name, liabilityType, outstandingBalance: { amount, currency }, valuedOn })).then((result) => { if (result) { setName(""); setAmount(""); } });
  return <Screen testID="finance-liabilities-screen"><PageHeader eyebrow="Balance sheet" title="Liabilities" description="Track balances you enter manually. Aperture does not contact lenders or infer accrued interest." /><ErrorBanner error={query.error ?? action.error} /><Panel title="Add liability"><TextField label="Liability name" name="liability-name" value={name} onChangeText={setName} required /><ChoiceField label="Liability type" value={liabilityType} onChange={setLiabilityType} options={liabilityTypes.map((value) => ({ value, label: value.replaceAll("_", " ") }))} /><TextField label="Outstanding balance" name="liability-value" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" required /><TextField label="Currency" name="liability-currency" value={currency} onChangeText={(value) => setCurrency(value.toUpperCase())} autoCapitalize="characters" required /><TextField label="Valued on" name="liability-date" value={valuedOn} onChangeText={setValuedOn} hint="Use YYYY-MM-DD." required /><ActionButton label="Add liability" pending={action.pending} onPress={submit} /></Panel><Panel title="Recorded liabilities">{query.loading || !query.data ? <LoadingState /> : query.data.items.length === 0 ? <EmptyState title="No liabilities" description="Add a manually recorded balance above." /> : <RecordList items={query.data.items} keyExtractor={(item) => item.id} accessibilityLabel="Recorded liabilities" renderItem={(item) => <RecordCard title={item.name} status={item.status} details={[`${formatMoney(item.outstandingBalance)} · valued ${item.valuedOn}`]}>{item.status === "active" ? <ActionButton label="Archive" tone="danger" onPress={() => void action.execute(() => service.liabilities.archive(context, item.id))} /> : null}</RecordCard>} />}</Panel></Screen>;
}
