import { useCallback, useState } from "react";
import { ActionButton, EmptyState, ErrorBanner, LoadingState, PageHeader, Panel, RecordCard, RecordList, Screen, TextField, formatMoney } from "../components/ui";
import { useFinanceAction } from "../hooks/use-finance-action"; import { useFinanceQuery } from "../hooks/use-finance-query"; import { useFinance } from "../providers/finance-provider";

export function LoansScreen() {
  const { service, context } = useFinance(); const action = useFinanceAction(); const [name, setName] = useState(""); const [principal, setPrincipal] = useState(""); const [outstanding, setOutstanding] = useState(""); const [currency, setCurrency] = useState("USD"); const [startedOn, setStartedOn] = useState(new Date().toISOString().slice(0, 10)); const [endsOn, setEndsOn] = useState(new Date().toISOString().slice(0, 10));
  const load = useCallback(() => service.loans.list(context), [service, context]); const query = useFinanceQuery(load);
  const submit = () => void action.execute(() => service.loans.create(context, { name, principal: { amount: principal, currency }, outstandingBalance: { amount: outstanding, currency }, startedOn, endsOn })).then((result) => { if (result) { setName(""); setPrincipal(""); setOutstanding(""); } });
  return <Screen testID="finance-loans-screen"><PageHeader eyebrow="Borrowing records" title="Loans" description="Track principal and remaining balances. Payment schedules belong in the Calculator Hub and use only assumptions you supply." /><ErrorBanner error={query.error ?? action.error} /><Panel title="Add loan"><TextField label="Loan name" name="loan-name" value={name} onChangeText={setName} required /><TextField label="Principal" name="loan-principal" value={principal} onChangeText={setPrincipal} keyboardType="decimal-pad" required /><TextField label="Outstanding balance" name="loan-outstanding" value={outstanding} onChangeText={setOutstanding} keyboardType="decimal-pad" required /><TextField label="Currency" name="loan-currency" value={currency} onChangeText={(value) => setCurrency(value.toUpperCase())} autoCapitalize="characters" required /><TextField label="Started on" name="loan-start" value={startedOn} onChangeText={setStartedOn} hint="Use YYYY-MM-DD." required /><TextField label="Ends on" name="loan-end" value={endsOn} onChangeText={setEndsOn} hint="Use YYYY-MM-DD." required /><ActionButton label="Add loan" pending={action.pending} onPress={submit} /></Panel><Panel title="Recorded loans">{query.loading || !query.data ? <LoadingState /> : query.data.items.length === 0 ? <EmptyState title="No loans" description="Add a loan balance above." /> : <RecordList items={query.data.items} keyExtractor={(item) => item.id} accessibilityLabel="Recorded loans" renderItem={(item) => <RecordCard title={item.name} status={item.status} details={[`${formatMoney(item.outstandingBalance)} remaining from ${formatMoney(item.principal)}`]}>{item.status === "active" ? <ActionButton label="Close" tone="secondary" onPress={() => void action.execute(() => service.loans.close(context, item.id))} /> : null}</RecordCard>} />}</Panel></Screen>;
}
