/* This file is generated by scripts/generate-investment-registry.mjs. Do not edit directly. */
import { brokeragePlugin } from "./brokerage.plugin.js";
import { cagrPlugin } from "./cagr.plugin.js";
import { fdPlugin } from "./fd.plugin.js";
import { lumpsumPlugin } from "./lumpsum.plugin.js";
import { marginPlugin } from "./margin.plugin.js";
import { mutualFundReturnsPlugin } from "./mutual-fund.plugin.js";
import { nscPlugin } from "./nsc.plugin.js";
import { postOfficeMisPlugin } from "./post-office-mis.plugin.js";
import { ppfPlugin } from "./ppf.plugin.js";
import { rdPlugin } from "./rd.plugin.js";
import { roiPlugin } from "./roi.plugin.js";
import { scssPlugin } from "./scss.plugin.js";
import { sipPlugin } from "./sip.plugin.js";
import { ssyPlugin } from "./ssy.plugin.js";
import { stepUpSipPlugin } from "./step-up-sip.plugin.js";
import { stockAveragePlugin } from "./stock-average.plugin.js";
import { swpPlugin } from "./swp.plugin.js";
import { xirrPlugin } from "./xirr.plugin.js";

export * from "./brokerage.plugin.js";
export * from "./cagr.plugin.js";
export * from "./fd.plugin.js";
export * from "./lumpsum.plugin.js";
export * from "./margin.plugin.js";
export * from "./mutual-fund.plugin.js";
export * from "./nsc.plugin.js";
export * from "./post-office-mis.plugin.js";
export * from "./ppf.plugin.js";
export * from "./rd.plugin.js";
export * from "./roi.plugin.js";
export * from "./scss.plugin.js";
export * from "./sip.plugin.js";
export * from "./ssy.plugin.js";
export * from "./step-up-sip.plugin.js";
export * from "./stock-average.plugin.js";
export * from "./swp.plugin.js";
export * from "./xirr.plugin.js";

export const investmentCalculatorPlugins = Object.freeze([
  brokeragePlugin,
  cagrPlugin,
  fdPlugin,
  lumpsumPlugin,
  marginPlugin,
  mutualFundReturnsPlugin,
  nscPlugin,
  postOfficeMisPlugin,
  ppfPlugin,
  rdPlugin,
  roiPlugin,
  scssPlugin,
  sipPlugin,
  ssyPlugin,
  stepUpSipPlugin,
  stockAveragePlugin,
  swpPlugin,
  xirrPlugin,
]);

const investmentCalculatorIds = new Set(investmentCalculatorPlugins.map((plugin) => plugin.manifest.id));
if (investmentCalculatorIds.size !== investmentCalculatorPlugins.length) {
  throw new Error("Investment calculator identifiers must be unique.");
}

export function getInvestmentCalculatorPlugin(id: string) {
  return investmentCalculatorPlugins.find((plugin) => plugin.manifest.id === id);
}
