import type { FinancialAccountRepository } from "../accounts/financial-account.repository.js";
import type { AssetRepository } from "../assets/asset.repository.js";
import type { BudgetLineRepository, BudgetRepository } from "../budgets/budget.repository.js";
import type { CalculatorScenarioRepository } from "../calculators/calculator.repository.js";
import type { TransactionCategoryRepository } from "../categories/transaction-category.repository.js";
import type { DividendRepository } from "../dividends/dividend.repository.js";
import type { FinancialDocumentRepository } from "../documents/financial-document.repository.js";
import type { FinancialGoalRepository } from "../financial-goals/financial-goal.repository.js";
import type { HoldingRepository } from "../holdings/holding.repository.js";
import type { FinancialImportRepository, FinancialImportRowRepository } from "../imports/financial-import.repository.js";
import type { IncomeSourceRepository } from "../income/income-source.repository.js";
import type { InsurancePolicyRepository } from "../insurance/insurance-policy.repository.js";
import type { InvestmentAccountRepository } from "../investments/investment-account.repository.js";
import type { LiabilityRepository } from "../liabilities/liability.repository.js";
import type { LoanPaymentRepository } from "../loan-payments/loan-payment.repository.js";
import type { LoanRepository } from "../loans/loan.repository.js";
import type { MarketPriceRepository } from "../market-prices/market-price.repository.js";
import type { NetWorthSnapshotRepository } from "../net-worth/net-worth.repository.js";
import type { RecurringTransactionRepository } from "../recurring-transactions/recurring-transaction.repository.js";
import type { TaxProfileRepository, TaxRecordRepository } from "../taxes/tax-record.repository.js";
import type { TradeRepository } from "../trades/trade.repository.js";
import type { TransactionRepository, TransactionSplitRepository } from "../transactions/transaction.repository.js";

export interface FinanceRepository {
  readonly accounts: FinancialAccountRepository;
  readonly transactions: TransactionRepository;
  readonly transactionSplits: TransactionSplitRepository;
  readonly categories: TransactionCategoryRepository;
  readonly budgets: BudgetRepository;
  readonly budgetLines: BudgetLineRepository;
  readonly recurringTransactions: RecurringTransactionRepository;
  readonly incomeSources: IncomeSourceRepository;
  readonly assets: AssetRepository;
  readonly liabilities: LiabilityRepository;
  readonly netWorthSnapshots: NetWorthSnapshotRepository;
  readonly investmentAccounts: InvestmentAccountRepository;
  readonly holdings: HoldingRepository;
  readonly trades: TradeRepository;
  readonly dividends: DividendRepository;
  readonly marketPrices: MarketPriceRepository;
  readonly loans: LoanRepository;
  readonly loanPayments: LoanPaymentRepository;
  readonly taxProfiles: TaxProfileRepository;
  readonly taxRecords: TaxRecordRepository;
  readonly insurancePolicies: InsurancePolicyRepository;
  readonly financialGoals: FinancialGoalRepository;
  readonly financialImports: FinancialImportRepository;
  readonly financialImportRows: FinancialImportRowRepository;
  readonly financialDocuments: FinancialDocumentRepository;
  readonly calculatorScenarios: CalculatorScenarioRepository;
}
