import type { DailyPlan, PlannerItem, PlannerItemType } from "@aperture/planner";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { apertureTheme } from "../../../theme/foundation";
import { usePlanner } from "../providers/planner-provider";

export function PlannerScreen() {
  const { service, context, clock, revision, refresh } = usePlanner();
  const [date, setDate] = useState(() => clock.now().slice(0, 10));
  const [title, setTitle] = useState("");
  const [type, setType] = useState<PlannerItemType>("task");
  const [priority, setPriority] = useState(2);
  const [dueDate, setDueDate] = useState("");
  const [repeat, setRepeat] = useState<"none" | "daily" | "weekly">("none");
  const [plan, setPlan] = useState<DailyPlan | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [pending, setPending] = useState(false);
  useEffect(() => {
    let active = true;
    const request = { context, date, revision };
    void service.getDailyPlan(request.context, request.date).then((value) => { if (active) { setPlan(value); setError(null); } }).catch((caught: unknown) => { if (active) setError(caught instanceof Error ? caught.message : "Unable to load planner."); });
    return () => { active = false; };
  }, [context, date, revision, service]);
  const items = useMemo(() => { const map = new Map<string, { item: PlannerItem; overdue: boolean }>(); for (const entry of [...(plan?.overdue ?? []), ...(plan?.scheduled ?? []), ...(plan?.completed ?? [])]) map.set(entry.item.id, entry); return [...map.values()]; }, [plan]);
  async function mutate(action: () => Promise<unknown>) { setPending(true); try { await action(); setError(null); refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update planner."); } finally { setPending(false); } }
  function create() { if (!title.trim()) { setError("Enter a title."); return; } void mutate(async () => { await service.createItem(context, { title: title.trim(), itemType: type, priority, scheduledFor: date, ...(dueDate ? { dueAt: `${dueDate}T23:59:59.000Z` } : {}), ...(repeat === "none" ? {} : { recurrence: { frequency: repeat, interval: 1 } }) }); setTitle(""); setDueDate(""); }); }
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.screen} keyboardShouldPersistTaps="handled">
    <View style={styles.header}><Text style={styles.eyebrow}>DAILY PLANNER</Text><Text style={styles.title}>Shape the day</Text><Text style={styles.copy}>Plan tasks, events, reminders, and repeatable focus work.</Text></View>
    {error ? <View style={styles.error} accessibilityRole="alert"><Text style={styles.errorText}>{error}</Text></View> : null}
    <View style={styles.summary}><View><Text style={styles.metric}>{plan?.scheduled.length ?? 0}</Text><Text style={styles.caption}>Open</Text></View><View><Text style={styles.metric}>{plan?.overdue.length ?? 0}</Text><Text style={styles.caption}>Overdue</Text></View><View><Text style={styles.metric}>{plan?.completed.length ?? 0}</Text><Text style={styles.caption}>Done</Text></View></View>
    <View style={styles.card}><Text style={styles.cardTitle}>Add to the plan</Text><Text style={styles.label}>Title</Text><TextInput accessibilityLabel="Planner item title" value={title} onChangeText={setTitle} style={styles.input} /><Text style={styles.label}>Scheduled date</Text><TextInput accessibilityLabel="Scheduled date" value={date} onChangeText={setDate} style={styles.input} placeholder="YYYY-MM-DD" /><Text style={styles.label}>Deadline date</Text><TextInput accessibilityLabel="Deadline date" value={dueDate} onChangeText={setDueDate} style={styles.input} placeholder="YYYY-MM-DD" /><Text style={styles.label}>Type</Text><View style={styles.wrap}>{(["task", "event", "reminder", "focus"] as const).map((value) => <Choice key={value} label={value} selected={type === value} onPress={() => setType(value)} />)}</View><Text style={styles.label}>Priority</Text><View style={styles.wrap}>{[1,2,3,4].map((value) => <Choice key={value} label={String(value)} selected={priority === value} onPress={() => setPriority(value)} />)}</View><Text style={styles.label}>Repeat</Text><View style={styles.wrap}>{(["none", "daily", "weekly"] as const).map((value) => <Choice key={value} label={value} selected={repeat === value} onPress={() => setRepeat(value)} />)}</View><Pressable accessibilityRole="button" disabled={pending} onPress={create} style={styles.primary}><Text style={styles.primaryText}>{pending ? "Saving…" : "Add item"}</Text></Pressable></View>
    <View style={styles.card}><Text style={styles.cardTitle}>{date}</Text>{plan === null ? <ActivityIndicator accessibilityLabel="Loading planner" /> : items.length === 0 ? <Text style={styles.empty}>Nothing planned for this date.</Text> : items.map(({ item, overdue }) => <View style={styles.item} key={item.id}><View style={styles.itemCopy}><Text style={styles.itemTitle}>{item.title}</Text><Text style={[styles.caption, overdue ? styles.overdue : null]}>{overdue ? "Overdue · " : ""}{item.itemType} · priority {item.priority}{item.recurrence ? ` · ${item.recurrence.frequency}` : ""}</Text></View><Pressable accessibilityRole="button" disabled={pending} onPress={() => void mutate(() => item.status === "completed" ? service.reopenItem(context, item.id) : service.completeItem(context, item.id))} style={styles.smallButton}><Text style={styles.smallButtonText}>{item.status === "completed" ? "Reopen" : "Done"}</Text></Pressable></View>)}</View>
  </ScrollView></SafeAreaView>;
}

function Choice({ label, selected, onPress }: { readonly label: string; readonly selected: boolean; readonly onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ selected }} onPress={onPress} style={[styles.choice, selected ? styles.choiceActive : null]}><Text style={[styles.choiceText, selected ? styles.choiceTextActive : null]}>{label}</Text></Pressable>; }

export const plannerStyles = StyleSheet.create({ safe: { flex: 1, backgroundColor: apertureTheme.colors.canvas }, screen: { padding: 20, paddingBottom: 70, gap: 16 }, header: { gap: 8 }, eyebrow: { color: "#47658a", fontWeight: "900", letterSpacing: 1.2, fontSize: 12 }, title: { color: apertureTheme.colors.ink, fontSize: 31, lineHeight: 37, fontWeight: "900" }, copy: { color: apertureTheme.colors.muted, lineHeight: 21 }, summary: { flexDirection: "row", justifyContent: "space-around", backgroundColor: "#e8eef7", borderRadius: 18, padding: 18 }, metric: { color: apertureTheme.colors.ink, fontSize: 28, fontWeight: "900", textAlign: "center" }, caption: { color: apertureTheme.colors.muted, fontSize: 13 }, card: { gap: 12, backgroundColor: "#fff", borderColor: "#ccd6e2", borderWidth: 1, borderRadius: 18, padding: 18 }, cardTitle: { color: apertureTheme.colors.ink, fontSize: 20, fontWeight: "900" }, label: { color: apertureTheme.colors.ink, fontWeight: "800" }, input: { minHeight: 48, borderColor: "#aebbc9", borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, color: apertureTheme.colors.ink }, wrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, choice: { borderColor: "#9eafc2", borderWidth: 1, borderRadius: 999, paddingHorizontal: 13, paddingVertical: 9 }, choiceActive: { backgroundColor: "#253a58" }, choiceText: { color: apertureTheme.colors.ink, fontWeight: "800", textTransform: "capitalize" }, choiceTextActive: { color: "#fff" }, primary: { minHeight: 48, alignItems: "center", justifyContent: "center", backgroundColor: "#38628e", borderRadius: 12 }, primaryText: { color: "#fff", fontWeight: "900" }, item: { flexDirection: "row", alignItems: "center", gap: 10, borderTopColor: "#e4e9ef", borderTopWidth: 1, paddingTop: 12 }, itemCopy: { flex: 1, gap: 4 }, itemTitle: { color: apertureTheme.colors.ink, fontSize: 16, fontWeight: "800" }, smallButton: { backgroundColor: "#e5edf7", borderRadius: 9, padding: 10 }, smallButtonText: { color: "#253a58", fontWeight: "900" }, overdue: { color: "#9a3030", fontWeight: "800" }, empty: { color: apertureTheme.colors.muted, fontStyle: "italic" }, error: { backgroundColor: "#fff0ee", borderRadius: 12, padding: 14 }, errorText: { color: "#8a2929", fontWeight: "700" } });
const styles = plannerStyles;
