module.exports = {
  preset: "jest-expo",
  testMatch: ["<rootDir>/tests/**/*.test.ts?(x)"],
  setupFilesAfterEnv: ["<rootDir>/tests/setup.ts"],
  collectCoverageFrom: ["src/features/{education,health,finance}/**/*.{ts,tsx}"],
  moduleNameMapper: {
    "^@aperture/auth$": "<rootDir>/../../packages/auth/dist/index.js",
    "^@aperture/calculators$": "<rootDir>/../../packages/calculators/dist/runtime.js",
    "^@aperture/education$": "<rootDir>/../../packages/education/dist/index.js",
    "^@aperture/education-memory$": "<rootDir>/../../packages/education-memory/dist/index.js",
    "^@aperture/education-memory/adapter-internals$": "<rootDir>/../../packages/education-memory/dist/adapter-internals.js",
    "^@aperture/health$": "<rootDir>/../../packages/health/dist/index.js",
    "^@aperture/health-memory$": "<rootDir>/../../packages/health-memory/dist/index.js",
    "^@aperture/health-memory/adapter-internals$": "<rootDir>/../../packages/health-memory/dist/adapter-internals.js",
    "^@aperture/finance$": "<rootDir>/../../packages/finance/dist/runtime.js",
    "^@aperture/finance-memory$": "<rootDir>/../../packages/finance-memory/dist/index.js",
    "^@aperture/finance-memory/adapter-internals$": "<rootDir>/../../packages/finance-memory/dist/adapter-internals.js",
    "^@aperture/postgres-repositories$": "<rootDir>/../../packages/postgres-repositories/dist/index.js",
    "^@aperture/supabase-repositories$": "<rootDir>/../../packages/supabase-repositories/dist/index.js",
    "^@aperture/validation$": "<rootDir>/../../packages/validation/dist/index.js",
  },
};
