"use client";

import { useCallback, type FormEvent } from "react";
import type { AssetType } from "@aperture/finance";
import { FinanceEmptyState, FinanceErrorBanner, FinanceLoadingState, FinancePageHeader, FinancePanel, FinanceSelectInput, FinanceStatusBadge, FinanceSubmitButton, FinanceTextInput, formatMoney } from "../components/ui";
import { useFinanceAction } from "../hooks/use-finance-action";
import { useFinanceQuery } from "../hooks/use-finance-query";
import { useFinance } from "../providers/finance-provider";

export function AssetsScreen() {
  const { service, context } = useFinance(); const action = useFinanceAction(); const load = useCallback(() => service.assets.list(context), [service, context]); const query = useFinanceQuery(load);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); void action.execute(() => service.assets.create(context, { name: String(form.get("name")), assetType: String(form.get("assetType")) as AssetType, currentValue: { amount: String(form.get("amount")), currency: String(form.get("currency")) }, valuedOn: String(form.get("valuedOn")) })).then((result) => { if (result) element.reset(); }); };
  return <><FinancePageHeader eyebrow="Balance sheet" title="Assets" description="Record the value and valuation date of assets without assuming market prices or converting currencies." /><FinanceErrorBanner error={query.error ?? action.error} /><div className="grid grid-2"><FinancePanel title="Add asset"><form className="form-grid" onSubmit={submit}><FinanceTextInput label="Asset name *" name="name" required /><FinanceSelectInput label="Asset type *" name="assetType"><option value="cash">cash</option><option value="property">property</option><option value="vehicle">vehicle</option><option value="investment">investment</option><option value="retirement">retirement</option><option value="other">other</option></FinanceSelectInput><FinanceTextInput label="Current value *" name="amount" required inputMode="decimal" /><FinanceTextInput label="Currency *" name="currency" defaultValue="USD" maxLength={3} required /><FinanceTextInput label="Valued on *" name="valuedOn" type="date" required /><FinanceSubmitButton pending={action.pending}>Add asset</FinanceSubmitButton></form></FinancePanel><FinancePanel title="Recorded assets">{query.loading || !query.data ? <FinanceLoadingState /> : query.data.items.length === 0 ? <FinanceEmptyState title="No assets" description="Add a manually valued asset above." /> : <ul className="record-list">{query.data.items.map((item) => <li className="record-card" key={item.id}><div><h3>{item.name}</h3><p>{formatMoney(item.currentValue)} · valued {item.valuedOn}</p></div><div className="record-actions"><FinanceStatusBadge value={item.status} />{item.status === "active" && <button className="button button-ghost" onClick={() => void action.execute(() => service.assets.archive(context, item.id))}>Archive</button>}</div></li>)}</ul>}</FinancePanel></div></>;
}
