"use client";

import { useCallback, type FormEvent } from "react";
import { FinanceEmptyState, FinanceErrorBanner, FinanceLoadingState, FinancePageHeader, FinancePanel, FinanceStatusBadge, FinanceSubmitButton, FinanceTextInput, formatMoney } from "../components/ui";
import { useFinanceAction } from "../hooks/use-finance-action";
import { useFinanceQuery } from "../hooks/use-finance-query";
import { useFinance } from "../providers/finance-provider";

export function GoalsScreen() {
  const { service, context } = useFinance(); const action = useFinanceAction(); const load = useCallback(() => service.goals.list(context), [service, context]); const query = useFinanceQuery(load);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); const currency = String(form.get("currency")); void action.execute(() => service.goals.create(context, { name: String(form.get("name")), targetAmount: { amount: String(form.get("target")), currency }, recordedProgressAmount: { amount: String(form.get("progress")) || "0", currency }, targetDate: String(form.get("targetDate")) })).then((result) => { if (result) element.reset(); }); };
  return <><FinancePageHeader eyebrow="Personal planning" title="Financial goals" description="Record a target and manually updated progress without recommendations or automated transfers." /><FinanceErrorBanner error={query.error ?? action.error} /><div className="grid grid-2"><FinancePanel title="Add goal"><form className="form-grid" onSubmit={submit}><FinanceTextInput label="Goal name *" name="name" required /><FinanceTextInput label="Target amount *" name="target" inputMode="decimal" required /><FinanceTextInput label="Recorded progress" name="progress" inputMode="decimal" defaultValue="0" /><FinanceTextInput label="Currency *" name="currency" defaultValue="USD" maxLength={3} required /><FinanceTextInput label="Target date *" name="targetDate" type="date" required /><FinanceSubmitButton pending={action.pending}>Add goal</FinanceSubmitButton></form></FinancePanel><FinancePanel title="Goal progress">{query.loading || !query.data ? <FinanceLoadingState /> : query.data.items.length === 0 ? <FinanceEmptyState title="No goals" description="Add a target above." /> : <ul className="record-list">{query.data.items.map((item) => <li className="record-card record-card-stack" key={item.id}><div><h3>{item.name}</h3><p>{formatMoney(item.recordedProgressAmount ?? { amount: "0", currency: item.targetAmount.currency })} of {formatMoney(item.targetAmount)} · due {item.targetDate}</p></div><div className="record-actions"><FinanceStatusBadge value={item.status} />{item.status === "active" && <button className="button button-secondary" onClick={() => void action.execute(() => service.goals.complete(context, item.id))}>Complete</button>}<button className="button button-ghost" onClick={() => void action.execute(() => service.goals.archive(context, item.id))}>Archive</button></div></li>)}</ul>}</FinancePanel></div></>;
}
