"use client";

import { useCallback, type FormEvent } from "react";
import { FinanceEmptyState, FinanceErrorBanner, FinanceLoadingState, FinancePageHeader, FinancePanel, FinanceSelectInput, FinanceStatusBadge, FinanceSubmitButton, FinanceTextInput } from "../components/ui";
import { useFinanceAction } from "../hooks/use-finance-action";
import { useFinanceQuery } from "../hooks/use-finance-query";
import { useFinance } from "../providers/finance-provider";

export function InvestmentsScreen() {
  const { service, context } = useFinance(); const action = useFinanceAction();
  const load = useCallback(async () => { const [accounts, investments] = await Promise.all([service.accounts.list(context), service.investmentAccounts.list(context)]); return { accounts: accounts.items.filter(({ accountType }) => accountType === "investment" || accountType === "retirement"), investments: investments.items }; }, [service, context]); const query = useFinanceQuery(load);
  const submitAccount = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); void action.execute(() => service.accounts.create(context, { name: String(form.get("accountName")), accountType: "investment", currency: String(form.get("accountCurrency")) })).then((result) => { if (result) element.reset(); }); };
  const submitInvestment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); const account = query.data?.accounts.find(({ id }) => id === String(form.get("financialAccountId"))); void action.execute(() => service.investmentAccounts.create(context, { financialAccountId: String(form.get("financialAccountId")), name: String(form.get("name")), currency: account?.currency ?? String(form.get("currency")) })).then((result) => { if (result) element.reset(); }); };
  return <><FinancePageHeader eyebrow="Investment records" title="Investments" description="Create manual investment-account records. Holdings and market feeds arrive in later infrastructure work." /><FinanceErrorBanner error={query.error ?? action.error} /><div className="grid grid-2"><FinancePanel title="Add investment financial account"><form className="form-grid" onSubmit={submitAccount}><FinanceTextInput label="Account name *" name="accountName" required /><FinanceTextInput label="Currency *" name="accountCurrency" defaultValue="USD" maxLength={3} required /><FinanceSubmitButton pending={action.pending}>Add financial account</FinanceSubmitButton></form></FinancePanel><FinancePanel title="Add investment account"><form className="form-grid" onSubmit={submitInvestment}><FinanceSelectInput label="Linked financial account *" name="financialAccountId" required><option value="">Choose account</option>{query.data?.accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</FinanceSelectInput><FinanceTextInput label="Investment account name *" name="name" required /><FinanceTextInput label="Fallback currency" name="currency" defaultValue="USD" maxLength={3} /><FinanceSubmitButton pending={action.pending}>Add investment account</FinanceSubmitButton></form></FinancePanel></div><FinancePanel title="Investment accounts">{query.loading || !query.data ? <FinanceLoadingState /> : query.data.investments.length === 0 ? <FinanceEmptyState title="No investment accounts" description="Create a linked financial account and investment record above." /> : <ul className="record-list">{query.data.investments.map((item) => <li className="record-card" key={item.id}><div><h3>{item.name}</h3><p>{item.currency} · linked account {item.financialAccountId}</p></div><div className="record-actions"><FinanceStatusBadge value={item.status} />{item.status === "active" && <button className="button button-ghost" onClick={() => void action.execute(() => service.investmentAccounts.archive(context, item.id))}>Archive</button>}</div></li>)}</ul>}</FinancePanel></>;
}
