"use client";

import { useCallback, type FormEvent } from "react";
import type { LiabilityType } from "@aperture/finance";
import { FinanceEmptyState, FinanceErrorBanner, FinanceLoadingState, FinancePageHeader, FinancePanel, FinanceSelectInput, FinanceStatusBadge, FinanceSubmitButton, FinanceTextInput, formatMoney } from "../components/ui";
import { useFinanceAction } from "../hooks/use-finance-action";
import { useFinanceQuery } from "../hooks/use-finance-query";
import { useFinance } from "../providers/finance-provider";

export function LiabilitiesScreen() {
  const { service, context } = useFinance(); const action = useFinanceAction(); const load = useCallback(() => service.liabilities.list(context), [service, context]); const query = useFinanceQuery(load);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); void action.execute(() => service.liabilities.create(context, { name: String(form.get("name")), liabilityType: String(form.get("liabilityType")) as LiabilityType, outstandingBalance: { amount: String(form.get("amount")), currency: String(form.get("currency")) }, valuedOn: String(form.get("valuedOn")) })).then((result) => { if (result) element.reset(); }); };
  return <><FinancePageHeader eyebrow="Balance sheet" title="Liabilities" description="Track balances you enter manually. Aperture does not contact lenders or infer accrued interest." /><FinanceErrorBanner error={query.error ?? action.error} /><div className="grid grid-2"><FinancePanel title="Add liability"><form className="form-grid" onSubmit={submit}><FinanceTextInput label="Liability name *" name="name" required /><FinanceSelectInput label="Liability type *" name="liabilityType"><option value="mortgage">mortgage</option><option value="personal_loan">personal loan</option><option value="auto_loan">auto loan</option><option value="credit_card">credit card</option><option value="tax">tax</option><option value="other">other</option></FinanceSelectInput><FinanceTextInput label="Outstanding balance *" name="amount" required inputMode="decimal" /><FinanceTextInput label="Currency *" name="currency" defaultValue="USD" maxLength={3} required /><FinanceTextInput label="Valued on *" name="valuedOn" type="date" required /><FinanceSubmitButton pending={action.pending}>Add liability</FinanceSubmitButton></form></FinancePanel><FinancePanel title="Recorded liabilities">{query.loading || !query.data ? <FinanceLoadingState /> : query.data.items.length === 0 ? <FinanceEmptyState title="No liabilities" description="Add a manually recorded balance above." /> : <ul className="record-list">{query.data.items.map((item) => <li className="record-card" key={item.id}><div><h3>{item.name}</h3><p>{formatMoney(item.outstandingBalance)} · valued {item.valuedOn}</p></div><div className="record-actions"><FinanceStatusBadge value={item.status} />{item.status === "active" && <button className="button button-ghost" onClick={() => void action.execute(() => service.liabilities.archive(context, item.id))}>Archive</button>}</div></li>)}</ul>}</FinancePanel></div></>;
}
