"use client";

import { useCallback, type FormEvent } from "react";
import { FinanceEmptyState, FinanceErrorBanner, FinanceLoadingState, FinancePageHeader, FinancePanel, FinanceStatusBadge, FinanceSubmitButton, FinanceTextInput, formatMoney } from "../components/ui";
import { useFinanceAction } from "../hooks/use-finance-action";
import { useFinanceQuery } from "../hooks/use-finance-query";
import { useFinance } from "../providers/finance-provider";

export function LoansScreen() {
  const { service, context } = useFinance(); const action = useFinanceAction(); const load = useCallback(() => service.loans.list(context), [service, context]); const query = useFinanceQuery(load);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); const currency = String(form.get("currency")); void action.execute(() => service.loans.create(context, { name: String(form.get("name")), principal: { amount: String(form.get("principal")), currency }, outstandingBalance: { amount: String(form.get("outstanding")), currency }, startedOn: String(form.get("startedOn")), endsOn: String(form.get("endsOn")) })).then((result) => { if (result) element.reset(); }); };
  return <><FinancePageHeader eyebrow="Borrowing records" title="Loans" description="Track principal and remaining balances. Payment schedules belong in the Calculator Hub and use only assumptions you supply." /><FinanceErrorBanner error={query.error ?? action.error} /><div className="grid grid-2"><FinancePanel title="Add loan"><form className="form-grid" onSubmit={submit}><FinanceTextInput label="Loan name *" name="name" required /><FinanceTextInput label="Principal *" name="principal" inputMode="decimal" required /><FinanceTextInput label="Outstanding balance *" name="outstanding" inputMode="decimal" required /><FinanceTextInput label="Currency *" name="currency" defaultValue="USD" maxLength={3} required /><FinanceTextInput label="Started on *" name="startedOn" type="date" required /><FinanceTextInput label="Ends on *" name="endsOn" type="date" required /><FinanceSubmitButton pending={action.pending}>Add loan</FinanceSubmitButton></form></FinancePanel><FinancePanel title="Recorded loans">{query.loading || !query.data ? <FinanceLoadingState /> : query.data.items.length === 0 ? <FinanceEmptyState title="No loans" description="Add a loan balance above." /> : <ul className="record-list">{query.data.items.map((item) => <li className="record-card" key={item.id}><div><h3>{item.name}</h3><p>{formatMoney(item.outstandingBalance)} remaining from {formatMoney(item.principal)}</p></div><div className="record-actions"><FinanceStatusBadge value={item.status} />{item.status === "active" && <button className="button button-secondary" onClick={() => void action.execute(() => service.loans.close(context, item.id))}>Close</button>}</div></li>)}</ul>}</FinancePanel></div></>;
}
