import { useCallback, useMemo, useState } from "react";
import { ActionButton, EmptyState, ErrorBanner, LoadingState, Metric, PageHeader, Panel, PreviewNotice, RecordCard, RecordList, Screen, TextField } from "../components/ui";
import { useHealthAction } from "../hooks/use-health-action";
import { useHealthQuery } from "../hooks/use-health-query";
import { useHealth } from "../providers/health-provider";
import { formatHealthDateTime, formatHealthQuantity, toHealthIsoTimestamp } from "../view-models/formatting";

const RANGE = { startsAt: "2000-01-01T00:00:00Z", endsAt: "2100-12-31T23:59:59Z" } as const;

export function HydrationScreen() {
  const { service, context } = useHealth(); const action = useHealthAction(); const [volume, setVolume] = useState(""); const [consumedAt, setConsumedAt] = useState(""); const [dateFilter, setDateFilter] = useState("");
  const load = useCallback(async () => { const [entries, summary] = await Promise.all([service.listHydrationEntries(context), service.getHydrationSummary({ ownerId: context.ownerId, range: RANGE })]); return { entries: entries.items, summary }; }, [service, context]); const query = useHealthQuery(load); const visible = useMemo(() => (query.data?.entries ?? []).filter((item) => !dateFilter || item.consumedAt.slice(0, 10) === dateFilter), [query.data, dateFilter]);
  const submit = () => void action.execute(() => service.recordHydration(context, { volume: { value: volume, unit: "milliliter" }, consumedAt: toHealthIsoTimestamp(consumedAt) })).then((saved) => { if (saved) { setVolume(""); setConsumedAt(""); } });
  return <Screen testID="health-hydration-screen"><PageHeader title="Hydration" description="Track consumed volumes and service-calculated totals without intake targets." /><PreviewNotice /><Panel title="Record hydration"><TextField name="hydrationVolume" label="Volume in milliliters" required value={volume} onChangeText={setVolume} keyboardType="decimal-pad" error={action.error?.fieldErrors.volume} /><TextField name="hydrationConsumedAt" label="Hydration consumed at" required value={consumedAt} onChangeText={setConsumedAt} placeholder="YYYY-MM-DDTHH:mm:ssZ" error={action.error?.fieldErrors.consumedAt} /><ErrorBanner error={action.error} /><ActionButton label="Record hydration" pending={action.pending} onPress={submit} /></Panel><Panel title="Hydration summary" description="Calculated by the shared Health service."><Metric label="Total hydration" value={formatHealthQuantity(query.data?.summary.totalVolume)} detail={`${query.data?.summary.entryCount ?? 0} records`} /></Panel><Panel title="Hydration history"><TextField name="hydrationDateFilter" label="Hydration date filter" value={dateFilter} onChangeText={setDateFilter} placeholder="YYYY-MM-DD" />{query.loading ? <LoadingState /> : !visible.length ? <EmptyState title="No hydration entries found" description="Record a drink or change the filter." /> : <RecordList items={visible} keyExtractor={(item) => item.id} accessibilityLabel="Hydration records" renderItem={(item) => <RecordCard title={formatHealthQuantity(item.volume)} details={[formatHealthDateTime(item.consumedAt)]}><ActionButton label={`Delete hydration from ${item.consumedAt}`} tone="danger" pending={action.pending} onPress={() => void action.execute(() => service.deleteHydrationEntry(context, item.id))} /></RecordCard>} />}<ErrorBanner error={query.error} /></Panel></Screen>;
}
