import { useCallback, useMemo, useState } from "react";
import type { ActivityRoute, Equipment, RunningActivity, WorkoutSession } from "@aperture/health";
import { ActionButton, ChoiceField, EmptyState, ErrorBanner, LoadingState, PageHeader, Panel, PreviewNotice, RecordCard, RecordList, Screen, TextField } from "../components/ui";
import { useHealthAction } from "../hooks/use-health-action";
import { useHealthQuery } from "../hooks/use-health-query";
import { useHealth } from "../providers/health-provider";
import { formatHealthDateTime, formatHealthQuantity, toHealthIsoTimestamp } from "../view-models/formatting";

interface RunningData { readonly routes: readonly ActivityRoute[]; readonly equipment: readonly Equipment[]; readonly workouts: readonly WorkoutSession[]; readonly activities: readonly RunningActivity[] }

export function RunningScreen() {
  const { service, context, clock } = useHealth(); const action = useHealthAction();
  const [routeTitle, setRouteTitle] = useState(""); const [routeDistance, setRouteDistance] = useState(""); const [equipmentName, setEquipmentName] = useState("");
  const [runTitle, setRunTitle] = useState(""); const [startedAt, setStartedAt] = useState(""); const [routeId, setRouteId] = useState(""); const [equipmentId, setEquipmentId] = useState(""); const [workoutId, setWorkoutId] = useState("");
  const [resultId, setResultId] = useState(""); const [resultDistance, setResultDistance] = useState(""); const [resultDuration, setResultDuration] = useState(""); const [statusFilter, setStatusFilter] = useState("all");
  const load = useCallback(async (): Promise<RunningData> => { const [routes, equipment, workouts, activities] = await Promise.all([service.listActivityRoutes(context), service.listEquipment(context), service.listWorkoutSessions(context), service.listRunningActivities(context)]); return { routes: routes.items, equipment: equipment.items, workouts: workouts.items, activities: activities.items }; }, [service, context]);
  const query = useHealthQuery(load); const visible = useMemo(() => (query.data?.activities ?? []).filter((item) => statusFilter === "all" || item.status === statusFilter), [query.data, statusFilter]);
  const createRoute = () => void action.execute(() => service.createActivityRoute(context, { title: routeTitle, ...(routeDistance ? { distance: { value: routeDistance, unit: "kilometer" as const } } : {}) })).then((saved) => { if (saved) { setRouteTitle(""); setRouteDistance(""); } });
  const createEquipment = () => void action.execute(() => service.createEquipment(context, { name: equipmentName, category: "running_shoes" })).then((saved) => { if (saved) setEquipmentName(""); });
  const createRun = () => void action.execute(() => service.createRunningActivity(context, { title: runTitle, startedAt: toHealthIsoTimestamp(startedAt), ...(routeId ? { routeId } : {}), ...(equipmentId ? { equipmentIds: [equipmentId] } : {}), ...(workoutId ? { workoutSessionId: workoutId } : {}) })).then((saved) => { if (saved) { setRunTitle(""); setStartedAt(""); } });
  const saveResult = () => void action.execute(() => service.updateRunningActivity(context, resultId, { distance: { value: resultDistance, unit: "kilometer" }, duration: { value: resultDuration, unit: "minute" } })).then((saved) => { if (saved) { setResultDistance(""); setResultDuration(""); } });
  const recordUsage = () => void action.execute(() => service.recordEquipmentUsage(context, { equipmentId, ...(resultId ? { runningActivityId: resultId } : {}), distance: { value: resultDistance, unit: "kilometer" }, duration: { value: resultDuration, unit: "minute" } }));
  return <Screen testID="health-running-screen"><PageHeader title="Running" description="Manage routes, equipment, activities, results, and factual usage totals." /><PreviewNotice /><ErrorBanner error={query.error ?? action.error} />
    <Panel title="Create route"><TextField name="routeTitle" label="Route title" required value={routeTitle} onChangeText={setRouteTitle} /><TextField name="routeDistance" label="Route distance in km" value={routeDistance} onChangeText={setRouteDistance} keyboardType="decimal-pad" /><ActionButton label="Create route" pending={action.pending} onPress={createRoute} /></Panel>
    <Panel title="Add running equipment"><TextField name="equipmentName" label="Equipment name" required value={equipmentName} onChangeText={setEquipmentName} /><ActionButton label="Create running equipment" pending={action.pending} onPress={createEquipment} /></Panel>
    <Panel title="Create running activity"><TextField name="runTitle" label="Run title" required value={runTitle} onChangeText={setRunTitle} /><TextField name="startedAt" label="Run started at" required value={startedAt} onChangeText={setStartedAt} placeholder="YYYY-MM-DDTHH:mm:ssZ" />{query.data?.routes.length ? <ChoiceField label="Running route" value={routeId} options={query.data.routes.map((item) => ({ value: item.id, label: item.title }))} onChange={setRouteId} /> : null}{query.data?.equipment.length ? <ChoiceField label="Running equipment" value={equipmentId} options={query.data.equipment.filter((item) => item.status === "active").map((item) => ({ value: item.id, label: item.name }))} onChange={setEquipmentId} /> : null}{query.data?.workouts.length ? <ChoiceField label="Linked workout" value={workoutId} options={query.data.workouts.map((item) => ({ value: item.id, label: item.title }))} onChange={setWorkoutId} /> : null}<ActionButton label="Create running activity" pending={action.pending} onPress={createRun} /></Panel>
    <Panel title="Save result or usage" description="Choose an activity and equipment after creating them.">{query.data?.activities.length ? <ChoiceField label="Result activity" value={resultId} options={query.data.activities.filter((item) => item.status !== "completed").map((item) => ({ value: item.id, label: item.title }))} onChange={setResultId} /> : null}<TextField name="resultDistance" label="Result distance in km" value={resultDistance} onChangeText={setResultDistance} keyboardType="decimal-pad" /><TextField name="resultDuration" label="Result duration in minutes" value={resultDuration} onChangeText={setResultDuration} keyboardType="decimal-pad" /><ActionButton label="Save running result" pending={action.pending} disabled={!resultId} onPress={saveResult} /><ActionButton label="Record equipment usage" tone="secondary" pending={action.pending} disabled={!equipmentId || !resultDistance || !resultDuration} onPress={recordUsage} /></Panel>
    <Panel title="Routes">{query.loading ? <LoadingState /> : !query.data?.routes.length ? <EmptyState title="No routes" description="Create a route above." /> : <RecordList items={query.data.routes} keyExtractor={(item) => item.id} accessibilityLabel="Running route records" renderItem={(item) => <RecordCard title={item.title} details={[formatHealthQuantity(item.distance)]}><ActionButton label={`Delete route ${item.title}`} tone="danger" pending={action.pending} onPress={() => void action.execute(() => service.deleteActivityRoute(context, item.id))} /></RecordCard>} />}</Panel>
    <Panel title="Equipment">{!query.data?.equipment.length ? <EmptyState title="No equipment" description="Add running equipment above." /> : <RecordList items={query.data.equipment} keyExtractor={(item) => item.id} accessibilityLabel="Running equipment records" renderItem={(item) => <RecordCard title={item.name} status={item.status} details={[item.category.replaceAll("_", " ")]}>{item.status === "active" ? <ActionButton label={`Retire ${item.name}`} tone="secondary" pending={action.pending} onPress={() => void action.execute(() => service.retireEquipment(context, item.id))} /> : null}</RecordCard>} />}</Panel>
    <Panel title="Running activities"><ChoiceField label="Running status filter" value={statusFilter} options={["all", "planned", "in_progress", "completed"].map((value) => ({ value, label: value.replaceAll("_", " ") }))} onChange={setStatusFilter} />{!visible.length ? <EmptyState title="No running activities found" description="Create a run or change the filter." /> : <RecordList items={visible} keyExtractor={(item) => item.id} accessibilityLabel="Running activity records" renderItem={(item) => <RecordCard title={item.title} status={item.status} details={[formatHealthDateTime(item.startedAt), formatHealthQuantity(item.distance), formatHealthQuantity(item.duration)]}>{item.status !== "completed" ? <ActionButton label={`Complete ${item.title}`} pending={action.pending} onPress={() => void action.execute(() => service.completeRunningActivity(context, item.id, clock.now()))} /> : null}<ActionButton label={`Delete ${item.title}`} tone="danger" pending={action.pending} onPress={() => void action.execute(() => service.deleteRunningActivity(context, item.id))} /></RecordCard>} />}</Panel>
  </Screen>;
}
