import { useCallback, useState } from "react";
import { ActionButton, ChoiceField, EmptyState, ErrorBanner, LoadingState, Metric, PageHeader, Panel, PreviewNotice, RecordCard, RecordList, Screen, TextField } from "../components/ui";
import { useHealthAction } from "../hooks/use-health-action";
import { useHealthQuery } from "../hooks/use-health-query";
import { useHealth } from "../providers/health-provider";
import { formatHealthDateTime, formatHealthQuantity, toHealthIsoTimestamp } from "../view-models/formatting";

const RANGE = { startsAt: "2000-01-01T00:00:00Z", endsAt: "2100-12-31T23:59:59Z" } as const;

export function SleepScreen() {
  const { service, context } = useHealth(); const action = useHealthAction();
  const [startedAt, setStartedAt] = useState(""); const [endedAt, setEndedAt] = useState(""); const [duration, setDuration] = useState(""); const [quality, setQuality] = useState<"poor" | "fair" | "good" | "excellent">("good");
  const load = useCallback(async () => { const [records, summary] = await Promise.all([service.listSleepRecords(context), service.getSleepSummary({ ownerId: context.ownerId, range: RANGE })]); return { records: records.items, summary }; }, [service, context]); const query = useHealthQuery(load);
  const submit = () => void action.execute(() => service.recordSleep(context, { startedAt: toHealthIsoTimestamp(startedAt), endedAt: toHealthIsoTimestamp(endedAt), quality, ...(duration ? { duration: { value: duration, unit: "minute" as const } } : {}) })).then((saved) => { if (saved) { setStartedAt(""); setEndedAt(""); setDuration(""); } });
  return <Screen testID="health-sleep-screen"><PageHeader title="Sleep" description="Record sleep timing, duration, and a personal quality rating without interpretation." /><PreviewNotice /><Panel title="Record sleep"><TextField name="sleepStartedAt" label="Sleep started at" required value={startedAt} onChangeText={setStartedAt} placeholder="YYYY-MM-DDTHH:mm:ssZ" error={action.error?.fieldErrors.startedAt} /><TextField name="sleepEndedAt" label="Sleep ended at" required value={endedAt} onChangeText={setEndedAt} placeholder="YYYY-MM-DDTHH:mm:ssZ" error={action.error?.fieldErrors.endedAt} /><TextField name="sleepDuration" label="Sleep duration in minutes" value={duration} onChangeText={setDuration} keyboardType="decimal-pad" /><ChoiceField label="Sleep quality" value={quality} options={["poor", "fair", "good", "excellent"].map((value) => ({ value: value as typeof quality, label: value }))} onChange={setQuality} /><ErrorBanner error={action.error} /><ActionButton label="Record sleep" pending={action.pending} onPress={submit} /></Panel><Panel title="Sleep summary" description="Calculated by the shared Health service."><Metric label="Recorded sleep" value={formatHealthQuantity(query.data?.summary.totalDuration)} detail={`${query.data?.summary.recordCount ?? 0} records`} /></Panel><Panel title="Sleep history"><ErrorBanner error={query.error} />{query.loading ? <LoadingState /> : !query.data?.records.length ? <EmptyState title="No sleep records" description="Record sleep above." /> : <RecordList items={query.data.records} keyExtractor={(item) => item.id} accessibilityLabel="Sleep records" renderItem={(item) => <RecordCard title={item.quality ?? "Unrated sleep"} details={[`${formatHealthDateTime(item.startedAt)} to ${formatHealthDateTime(item.endedAt)}`, formatHealthQuantity(item.duration)]}><ActionButton label={`Delete sleep from ${item.startedAt}`} tone="danger" pending={action.pending} onPress={() => void action.execute(() => service.deleteSleep(context, item.id))} /></RecordCard>} />}</Panel></Screen>;
}
