import { useCallback, useMemo, useState } from "react";
import type { VitalReadingType, VitalReadingValue } from "@aperture/health";
import { ActionButton, ChoiceField, EmptyState, ErrorBanner, LoadingState, PageHeader, Panel, PreviewNotice, RecordCard, RecordList, Screen, TextField } from "../components/ui";
import { useHealthAction } from "../hooks/use-health-action";
import { useHealthQuery } from "../hooks/use-health-query";
import { useHealth } from "../providers/health-provider";
import { formatHealthDateTime, formatHealthQuantity, toHealthIsoTimestamp } from "../view-models/formatting";

const types: readonly VitalReadingType[] = ["resting_heart_rate", "blood_pressure", "blood_glucose", "oxygen_saturation", "body_temperature"];
function reading(type: VitalReadingType, primary: string, secondary: string): VitalReadingValue {
  switch (type) { case "resting_heart_rate": return { type, value: { value: Number(primary), unit: "beats_per_minute" } }; case "blood_pressure": return { type, value: { systolic: Number(primary), diastolic: Number(secondary), unit: "millimeters_of_mercury" } }; case "blood_glucose": return { type, value: { value: primary, unit: "milligrams_per_deciliter" } }; case "oxygen_saturation": return { type, value: { value: primary, unit: "percent" } }; case "body_temperature": return { type, value: { value: primary, unit: "celsius" } }; }
}
function valueText(value: VitalReadingValue) { return value.type === "blood_pressure" ? `${value.value.systolic}/${value.value.diastolic} millimeters of mercury` : formatHealthQuantity(value.value); }

export function VitalsScreen() {
  const { service, context } = useHealth(); const action = useHealthAction();
  const [type, setType] = useState<VitalReadingType>("resting_heart_rate"); const [primary, setPrimary] = useState(""); const [secondary, setSecondary] = useState(""); const [observedAt, setObservedAt] = useState(""); const [filter, setFilter] = useState<VitalReadingType | "all">("all");
  const load = useCallback(async () => (await service.listVitalReadings(context)).items, [service, context]); const query = useHealthQuery(load); const visible = useMemo(() => (query.data ?? []).filter((item) => filter === "all" || item.reading.type === filter), [query.data, filter]);
  const submit = () => void action.execute(() => service.recordVitalReading(context, { reading: reading(type, primary, secondary), observedAt: toHealthIsoTimestamp(observedAt) })).then((saved) => { if (saved) { setPrimary(""); setSecondary(""); setObservedAt(""); } });
  return <Screen testID="health-vitals-screen"><PageHeader title="Vital signs" description="Capture user-supplied readings as observations without diagnosis." /><PreviewNotice /><Panel title="Record vital"><ChoiceField label="Vital type" value={type} options={types.map((item) => ({ value: item, label: item.replaceAll("_", " ") }))} onChange={setType} required /><TextField name="primary" label={type === "blood_pressure" ? "Systolic" : "Value"} required value={primary} onChangeText={setPrimary} keyboardType="decimal-pad" />{type === "blood_pressure" ? <TextField name="secondary" label="Diastolic" required value={secondary} onChangeText={setSecondary} keyboardType="number-pad" /> : null}<TextField name="observedAt" label="Observed at" required value={observedAt} onChangeText={setObservedAt} placeholder="YYYY-MM-DDTHH:mm:ssZ" error={action.error?.fieldErrors.observedAt} /><ErrorBanner error={action.error} /><ActionButton label="Record vital" pending={action.pending} onPress={submit} /></Panel><Panel title="Vital history"><ChoiceField label="Vital filter" value={filter} options={[{ value: "all", label: "All" }, ...types.map((item) => ({ value: item, label: item.replaceAll("_", " ") }))]} onChange={setFilter} />{query.loading ? <LoadingState /> : !visible.length ? <EmptyState title="No vital readings found" description="Record a vital or change the filter." /> : <RecordList items={visible} keyExtractor={(item) => item.id} accessibilityLabel="Vital reading records" renderItem={(item) => <RecordCard title={item.reading.type.replaceAll("_", " ")} details={[valueText(item.reading), formatHealthDateTime(item.observedAt)]}><ActionButton label={`Delete ${item.reading.type.replaceAll("_", " ")} reading`} tone="danger" pending={action.pending} onPress={() => void action.execute(() => service.deleteVitalReading(context, item.id))} /></RecordCard>} />}<ErrorBanner error={query.error} /></Panel></Screen>;
}
