import { useCallback, useMemo, useState } from "react";
import type { Exercise, ExerciseSet, WorkoutPlan, WorkoutSession } from "@aperture/health";
import { ActionButton, ChoiceField, EmptyState, ErrorBanner, LoadingState, PageHeader, Panel, PreviewNotice, RecordCard, RecordList, Screen, TextField } from "../components/ui";
import { useHealthAction } from "../hooks/use-health-action";
import { useHealthQuery } from "../hooks/use-health-query";
import { useHealth } from "../providers/health-provider";
import { formatHealthDateTime, formatHealthQuantity, toHealthIsoTimestamp } from "../view-models/formatting";

interface WorkoutData { readonly exercises: readonly Exercise[]; readonly plans: readonly WorkoutPlan[]; readonly workouts: readonly WorkoutSession[]; readonly sets: readonly ExerciseSet[] }

export function WorkoutsScreen() {
  const { service, context, clock } = useHealth(); const action = useHealthAction();
  const [exerciseName, setExerciseName] = useState(""); const [exerciseCategory, setExerciseCategory] = useState<"strength" | "cardio" | "mobility" | "balance" | "other">("strength");
  const [planTitle, setPlanTitle] = useState(""); const [workoutTitle, setWorkoutTitle] = useState(""); const [scheduledAt, setScheduledAt] = useState(""); const [workoutPlanId, setWorkoutPlanId] = useState("");
  const [setWorkoutId, setSetWorkoutId] = useState(""); const [setExerciseId, setSetExerciseId] = useState(""); const [sequence, setSequence] = useState("1"); const [repetitions, setRepetitions] = useState(""); const [weight, setWeight] = useState(""); const [statusFilter, setStatusFilter] = useState("all");
  const load = useCallback(async (): Promise<WorkoutData> => { const [exercises, plans, workouts] = await Promise.all([service.listExercises(context), service.listWorkoutPlans(context), service.listWorkoutSessions(context)]); const setPages = await Promise.all(workouts.items.map((item) => service.listExerciseSetsByWorkout(context, { workoutSessionId: item.id }))); return { exercises: exercises.items, plans: plans.items, workouts: workouts.items, sets: setPages.flatMap((page) => page.items) }; }, [service, context]);
  const query = useHealthQuery(load); const visibleWorkouts = useMemo(() => (query.data?.workouts ?? []).filter((item) => statusFilter === "all" || item.status === statusFilter), [query.data, statusFilter]);
  const createExercise = () => void action.execute(() => service.createExercise(context, { name: exerciseName, category: exerciseCategory })).then((saved) => { if (saved) setExerciseName(""); });
  const createPlan = () => void action.execute(() => service.createWorkoutPlan(context, { title: planTitle })).then((saved) => { if (saved) setPlanTitle(""); });
  const createWorkout = () => void action.execute(() => service.createWorkoutSession(context, { title: workoutTitle, ...(scheduledAt ? { scheduledAt: toHealthIsoTimestamp(scheduledAt) } : {}), ...(workoutPlanId ? { workoutPlanId } : {}) })).then((saved) => { if (saved) { setWorkoutTitle(""); setScheduledAt(""); } });
  const createSet = () => void action.execute(() => service.recordExerciseSet(context, { workoutSessionId: setWorkoutId, exerciseId: setExerciseId, sequence: Number(sequence), ...(repetitions ? { repetitions: { value: Number(repetitions), unit: "repetition" as const } } : {}), ...(weight ? { weight: { value: weight, unit: "kilogram" as const } } : {}) })).then((saved) => { if (saved) { setSequence("1"); setRepetitions(""); setWeight(""); } });
  const exerciseLabel = (id: string) => query.data?.exercises.find((item) => item.id === id)?.name ?? "Unknown exercise";
  return <Screen testID="health-workouts-screen"><PageHeader title="Workouts" description="Manage exercises, plans, sessions, and sets through explicit service workflows." /><PreviewNotice /><ErrorBanner error={query.error ?? action.error} />
    <Panel title="Create exercise"><TextField name="exerciseName" label="Exercise name" required value={exerciseName} onChangeText={setExerciseName} error={action.error?.fieldErrors.name} /><ChoiceField label="Exercise category" value={exerciseCategory} options={["strength", "cardio", "mobility", "balance", "other"].map((value) => ({ value: value as typeof exerciseCategory, label: value }))} onChange={setExerciseCategory} /><ActionButton label="Create exercise" onPress={createExercise} pending={action.pending} /></Panel>
    <Panel title="Create workout plan"><TextField name="planTitle" label="Plan title" required value={planTitle} onChangeText={setPlanTitle} error={action.error?.fieldErrors.title} /><ActionButton label="Create workout plan" onPress={createPlan} pending={action.pending} /></Panel>
    <Panel title="Schedule workout"><TextField name="workoutTitle" label="Workout title" required value={workoutTitle} onChangeText={setWorkoutTitle} /><TextField name="scheduledAt" label="Scheduled at" value={scheduledAt} onChangeText={setScheduledAt} placeholder="YYYY-MM-DDTHH:mm:ssZ" />{query.data?.plans.length ? <ChoiceField label="Workout plan" value={workoutPlanId} options={query.data.plans.filter((item) => item.status !== "archived").map((item) => ({ value: item.id, label: item.title }))} onChange={setWorkoutPlanId} /> : null}<ActionButton label="Create workout" onPress={createWorkout} pending={action.pending} /></Panel>
    <Panel title="Record exercise set" description="Choose records owned by the authenticated account.">{query.data?.workouts.length ? <ChoiceField label="Set workout" value={setWorkoutId} options={query.data.workouts.map((item) => ({ value: item.id, label: item.title }))} onChange={setSetWorkoutId} required /> : null}{query.data?.exercises.length ? <ChoiceField label="Set exercise" value={setExerciseId} options={query.data.exercises.filter((item) => item.status === "active").map((item) => ({ value: item.id, label: item.name }))} onChange={setSetExerciseId} required /> : null}<TextField name="sequence" label="Set number" required value={sequence} onChangeText={setSequence} keyboardType="number-pad" /><TextField name="repetitions" label="Repetitions" value={repetitions} onChangeText={setRepetitions} keyboardType="number-pad" /><TextField name="weight" label="Weight in kg" value={weight} onChangeText={setWeight} keyboardType="decimal-pad" /><ActionButton label="Record exercise set" onPress={createSet} pending={action.pending} disabled={!setWorkoutId || !setExerciseId} /></Panel>
    <Panel title="Exercise catalog">{query.loading ? <LoadingState /> : !query.data?.exercises.length ? <EmptyState title="No exercises" description="Create an exercise above." /> : <RecordList items={query.data.exercises} keyExtractor={(item) => item.id} accessibilityLabel="Exercise records" renderItem={(item) => <RecordCard title={item.name} status={item.status} details={[item.category]}>{item.status === "active" ? <ActionButton label={`Archive ${item.name}`} tone="secondary" pending={action.pending} onPress={() => void action.execute(() => service.archiveExercise(context, item.id))} /> : null}</RecordCard>} />}</Panel>
    <Panel title="Workout plans">{!query.data?.plans.length ? <EmptyState title="No workout plans" description="Create a plan above." /> : <RecordList items={query.data.plans} keyExtractor={(item) => item.id} accessibilityLabel="Workout plan records" renderItem={(item) => <RecordCard title={item.title} status={item.status} details={[item.startsOn ?? "No start date"]}>{item.status === "draft" ? <ActionButton label={`Activate ${item.title}`} tone="secondary" pending={action.pending} onPress={() => void action.execute(() => service.activateWorkoutPlan(context, item.id))} /> : null}{item.status !== "archived" ? <ActionButton label={`Archive plan ${item.title}`} tone="secondary" pending={action.pending} onPress={() => void action.execute(() => service.archiveWorkoutPlan(context, item.id))} /> : null}</RecordCard>} />}</Panel>
    <Panel title="Workout sessions"><ChoiceField label="Workout status filter" value={statusFilter} options={["all", "planned", "in_progress", "paused", "completed", "cancelled"].map((value) => ({ value, label: value.replaceAll("_", " ") }))} onChange={setStatusFilter} />{!visibleWorkouts.length ? <EmptyState title="No workouts found" description="Create a session or change the filter." /> : <RecordList items={visibleWorkouts} keyExtractor={(item) => item.id} accessibilityLabel="Workout session records" renderItem={(item) => <RecordCard title={item.title} status={item.status} details={[formatHealthDateTime(item.scheduledAt), `${query.data?.sets.filter((set) => set.workoutSessionId === item.id).length ?? 0} sets`, ...(query.data?.sets.filter((set) => set.workoutSessionId === item.id).map((set) => `${exerciseLabel(set.exerciseId)} · ${formatHealthQuantity(set.weight)} · ${set.repetitions?.value ?? 0} reps`) ?? [])]}>{item.status === "planned" ? <ActionButton label={`Start ${item.title}`} tone="secondary" pending={action.pending} onPress={() => void action.execute(() => service.startWorkout(context, item.id, clock.now()))} /> : null}{item.status === "in_progress" ? <ActionButton label={`Pause ${item.title}`} tone="secondary" pending={action.pending} onPress={() => void action.execute(() => service.pauseWorkout(context, item.id, clock.now()))} /> : null}{item.status === "paused" ? <ActionButton label={`Resume ${item.title}`} tone="secondary" pending={action.pending} onPress={() => void action.execute(() => service.resumeWorkout(context, item.id, clock.now()))} /> : null}{item.status === "in_progress" || item.status === "paused" ? <ActionButton label={`Complete ${item.title}`} pending={action.pending} onPress={() => void action.execute(() => service.completeWorkout(context, item.id, clock.now()))} /> : null}{item.status !== "completed" && item.status !== "cancelled" ? <ActionButton label={`Cancel ${item.title}`} tone="danger" pending={action.pending} onPress={() => void action.execute(() => service.cancelWorkout(context, item.id))} /> : null}{query.data?.sets.filter((set) => set.workoutSessionId === item.id).map((set) => <ActionButton key={set.id} label={`Delete set ${String(set.sequence)}`} tone="danger" pending={action.pending} onPress={() => void action.execute(() => service.deleteExerciseSet(context, set.id))} />)}</RecordCard>} />}</Panel>
  </Screen>;
}
