import { featureRegistry } from "@aperture/feature-registry";
import type { UpdateSettingsInput, UserSettings } from "@aperture/settings";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Link, type Href } from "expo-router";
import { apertureTheme } from "../../theme/foundation";
import { useSettings } from "./provider";

function Toggle({ label, checked, locked = false, onPress }: { readonly label: string; readonly checked: boolean; readonly locked?: boolean; readonly onPress: () => void }) {
  return <Pressable accessibilityRole="switch" accessibilityLabel={label} accessibilityState={{ checked, disabled: locked }} disabled={locked} onPress={onPress} style={styles.toggle}><View><Text style={styles.toggleLabel}>{label}</Text>{locked ? <Text style={styles.required}>REQUIRED</Text> : null}</View><Text style={[styles.toggleValue, checked ? styles.enabled : null]}>{checked ? "On" : "Off"}</Text></Pressable>;
}

function Choice({ label, value, values, onSelect }: { readonly label: string; readonly value: string; readonly values: readonly string[]; readonly onSelect: (value: string) => void }) {
  return <View style={styles.field}><Text style={styles.label}>{label}</Text><View style={styles.wrap}>{values.map((item) => <Pressable accessibilityRole="radio" accessibilityState={{ selected: value === item }} key={item} onPress={() => onSelect(item)} style={[styles.chip, value === item ? styles.chipActive : null]}><Text style={[styles.chipText, value === item ? styles.chipTextActive : null]}>{item}</Text></Pressable>)}</View></View>;
}

export function SettingsShellScreen() {
  const { snapshot, loading, error, update, updatePlatform } = useSettings();
  if (loading) return <SafeAreaView style={styles.center}><ActivityIndicator accessibilityLabel="Loading settings" color={apertureTheme.colors.focus} /></SafeAreaView>;
  if (error || snapshot === null) return <SafeAreaView style={styles.center}><Text accessibilityRole="alert" style={styles.error}>{error ?? "Settings are unavailable."}</Text></SafeAreaView>;
  const settings = snapshot.preferences;
  const save = (input: UpdateSettingsInput) => { void update(input).catch(() => undefined); };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.screen}>
    <View style={styles.header}><Text style={styles.eyebrow}>SETTINGS & PRIVACY</Text><Text style={styles.title}>Shape your private workspace</Text><Text style={styles.copy}>Portable choices sync across devices. Mobile-only behavior stays on its own settings surface.</Text><Link href={"/settings/data" as Href} style={styles.dataLink}>Data & recovery</Link></View>
    <View style={styles.card}><Text style={styles.cardTitle}>Appearance & region</Text>
      <Choice label="Theme" value={settings.theme} values={["system", "light", "dark"]} onSelect={(value) => save({ theme: value as UserSettings["theme"] })} />
      <Text style={styles.label}>Locale</Text><TextInput accessibilityLabel="Locale" style={styles.input} defaultValue={settings.locale} onEndEditing={(event) => save({ locale: event.nativeEvent.text })} />
      <Text style={styles.label}>Timezone</Text><TextInput accessibilityLabel="Timezone" style={styles.input} defaultValue={settings.timeZone} onEndEditing={(event) => save({ timeZone: event.nativeEvent.text })} />
      <Text style={styles.label}>Currency</Text><TextInput accessibilityLabel="Currency" autoCapitalize="characters" maxLength={3} style={styles.input} defaultValue={settings.currency} onEndEditing={(event) => save({ currency: event.nativeEvent.text })} />
      <Choice label="Date format" value={settings.dateFormat} values={["locale-default", "day-month-year", "month-day-year", "year-month-day"]} onSelect={(value) => save({ dateFormat: value as UserSettings["dateFormat"] })} />
      <Choice label="Week starts" value={settings.weekStartDay} values={["monday", "sunday"]} onSelect={(value) => save({ weekStartDay: value as UserSettings["weekStartDay"] })} />
    </View>
    <View style={styles.card}><Text style={styles.cardTitle}>Units & planning</Text>
      <Choice label="Measurement system" value={settings.units.measurementSystem} values={["metric", "imperial"]} onSelect={(value) => save({ units: { measurementSystem: value as UserSettings["units"]["measurementSystem"] } })} />
      <Choice label="Temperature" value={settings.units.temperatureUnit} values={["celsius", "fahrenheit"]} onSelect={(value) => save({ units: { temperatureUnit: value as UserSettings["units"]["temperatureUnit"] } })} />
      <Choice label="Distance" value={settings.units.distanceUnit} values={["kilometres", "miles"]} onSelect={(value) => save({ units: { distanceUnit: value as UserSettings["units"]["distanceUnit"] } })} />
      <Choice label="Mass" value={settings.units.massUnit} values={["kilograms", "pounds"]} onSelect={(value) => save({ units: { massUnit: value as UserSettings["units"]["massUnit"] } })} />
      <Text style={styles.label}>Fiscal start month</Text><TextInput accessibilityLabel="Fiscal year start month" keyboardType="number-pad" style={styles.input} defaultValue={String(settings.fiscalYear.startMonth)} onEndEditing={(event) => save({ fiscalYear: { startMonth: Number(event.nativeEvent.text) } })} />
      <Text style={styles.label}>Fiscal start day</Text><TextInput accessibilityLabel="Fiscal year start day" keyboardType="number-pad" style={styles.input} defaultValue={String(settings.fiscalYear.startDay)} onEndEditing={(event) => save({ fiscalYear: { startDay: Number(event.nativeEvent.text) } })} />
      <Text style={styles.label}>GPA scale</Text><TextInput accessibilityLabel="GPA scale" keyboardType="decimal-pad" style={styles.input} defaultValue={String(settings.gpaScale)} onEndEditing={(event) => save({ gpaScale: Number(event.nativeEvent.text) })} />
    </View>
    <View style={styles.card}><Text style={styles.cardTitle}>Calculator defaults</Text><Text style={styles.label}>Inflation rate (%)</Text><TextInput accessibilityLabel="Inflation rate" keyboardType="decimal-pad" style={styles.input} defaultValue={String(settings.calculatorDefaults.inflationRate ?? 6)} onEndEditing={(event) => save({ calculatorDefaults: { inflationRate: Number(event.nativeEvent.text) } })} /><Text style={styles.label}>Expected return (%)</Text><TextInput accessibilityLabel="Expected return" keyboardType="decimal-pad" style={styles.input} defaultValue={String(settings.calculatorDefaults.expectedReturnRate ?? 10)} onEndEditing={(event) => save({ calculatorDefaults: { expectedReturnRate: Number(event.nativeEvent.text) } })} /></View>
    <View style={styles.card}><Text style={styles.cardTitle}>Privacy controls</Text><Text style={styles.copy}>Optional collection is off by default.</Text><Toggle label="Usage analytics" checked={settings.privacy.usageAnalytics} onPress={() => save({ privacy: { usageAnalytics: !settings.privacy.usageAnalytics } })} /><Toggle label="Crash reports" checked={settings.privacy.crashReports} onPress={() => save({ privacy: { crashReports: !settings.privacy.crashReports } })} /><Toggle label="Personalized insights" checked={settings.privacy.personalizedInsights} onPress={() => save({ privacy: { personalizedInsights: !settings.privacy.personalizedInsights } })} /><Toggle label="Integration data sharing" checked={settings.privacy.integrationDataSharing} onPress={() => save({ privacy: { integrationDataSharing: !settings.privacy.integrationDataSharing } })} /></View>
    <View style={styles.card}><Text style={styles.cardTitle}>Features</Text><Text style={styles.copy}>Hiding a workspace keeps its records intact.</Text>{featureRegistry.listFeatures().map((feature) => { const checked = feature.disableAllowed ? settings.featureEnablement[feature.id] ?? feature.defaultEnabled : true; return <Toggle key={feature.id} label={`${feature.displayName} feature`} locked={!feature.disableAllowed} checked={checked} onPress={() => save({ featureEnablement: { [feature.id]: !checked } })} />; })}</View>
    <View style={styles.card}><Text style={styles.cardTitle}>Today widgets</Text>{featureRegistry.widgets("mobile").map((widget) => { const checked = settings.dashboardWidgets[widget.id] ?? widget.defaultEnabled; return <Toggle key={widget.id} label={`${widget.title} widget`} checked={checked} onPress={() => save({ dashboardWidgets: { [widget.id]: !checked } })} />; })}</View>
    <View style={styles.card}><Text style={styles.cardTitle}>Mobile-only behavior</Text><Toggle label="Haptics" checked={settings.platform.mobile.haptics} onPress={() => { void updatePlatform({ haptics: !settings.platform.mobile.haptics }).catch(() => undefined); }} /><Toggle label="Reduce motion" checked={settings.platform.mobile.reduceMotion} onPress={() => { void updatePlatform({ reduceMotion: !settings.platform.mobile.reduceMotion }).catch(() => undefined); }} /></View>
    <View style={styles.card}><Text style={styles.cardTitle}>Integrations</Text><Text style={styles.copy}>Only connection health is shown. Credentials remain server-only.</Text>{snapshot.integrations.length === 0 ? <Text style={styles.empty}>No integrations connected.</Text> : snapshot.integrations.map((integration) => <View style={styles.integration} key={integration.id}><Text style={styles.toggleLabel}>{integration.integrationId}</Text><Text style={styles.enabled}>{integration.status}</Text></View>)}</View>
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: apertureTheme.colors.canvas }, screen: { padding: 20, paddingBottom: 70, gap: 16 }, center: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: apertureTheme.colors.canvas }, header: { gap: 8, paddingVertical: 8 }, eyebrow: { color: "#4d6470", fontSize: 12, fontWeight: "900", letterSpacing: 1.2 }, title: { color: apertureTheme.colors.ink, fontSize: 30, lineHeight: 36, fontWeight: "900" }, copy: { color: apertureTheme.colors.muted, lineHeight: 21 }, dataLink: { color: "#087f72", fontWeight: "900", paddingVertical: 8 }, card: { gap: 12, backgroundColor: "#fff", borderColor: "#ccd8d5", borderWidth: 1, borderRadius: 18, padding: 18 }, cardTitle: { color: apertureTheme.colors.ink, fontSize: 20, fontWeight: "900" }, field: { gap: 8 }, label: { color: apertureTheme.colors.ink, fontWeight: "800" }, input: { minHeight: 48, borderColor: "#aebfbb", borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, color: apertureTheme.colors.ink }, wrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { borderColor: "#9fb6b2", borderWidth: 1, borderRadius: 999, paddingHorizontal: 13, paddingVertical: 9 }, chipActive: { backgroundColor: apertureTheme.colors.ink }, chipText: { color: apertureTheme.colors.ink, fontWeight: "800" }, chipTextActive: { color: "#fff" }, toggle: { minHeight: 50, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderTopColor: "#e3e9e7", borderTopWidth: 1, paddingTop: 10 }, toggleLabel: { color: apertureTheme.colors.ink, fontWeight: "800" }, toggleValue: { color: apertureTheme.colors.muted, fontWeight: "900" }, enabled: { color: "#087f72", fontWeight: "900" }, required: { color: apertureTheme.colors.muted, fontSize: 10, fontWeight: "900", marginTop: 2 }, integration: { flexDirection: "row", justifyContent: "space-between", borderTopColor: "#e3e9e7", borderTopWidth: 1, paddingTop: 12 }, empty: { color: apertureTheme.colors.muted, fontStyle: "italic" }, error: { color: "#8a2929", fontWeight: "700" },
});
