import { useEffect, useState } from "react";
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { emptyPortfolioContent, PORTFOLIO_ENTRY_FIELDS, PORTFOLIO_PROFILE_FIELDS, PORTFOLIO_SECTIONS, portfolioErrorMessage, updatePortfolioEntry, type PortfolioContent, type PortfolioDraft } from "@aperture/portfolio";
import { usePortfolio } from "./provider";
export function PortfolioEditor() {
  const { ownerId, service } = usePortfolio(); const [draft, setDraft] = useState<PortfolioDraft | null>(null); const [content, setContent] = useState<PortfolioContent>(emptyPortfolioContent); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState(""); const [confirmation, setConfirmation] = useState("");
  const apply = (value: PortfolioDraft) => { setDraft(value); setContent(value.content); };
  useEffect(() => { let active = true; void service.getDraft(ownerId).then((value) => { if (active) { setDraft(value); setContent(value.content); } }).catch((failure: unknown) => { if (active) setError(portfolioErrorMessage(failure)); }); return () => { active = false; }; }, [ownerId, service]);
  async function perform(work: () => Promise<PortfolioDraft>, success: string) { setBusy(true); setError(null); setMessage(""); try { apply(await work()); setMessage(success); } catch (failure) { setError(portfolioErrorMessage(failure)); } finally { setBusy(false); } }
  const button = (label: string, work: () => void, disabled = false) => <Pressable accessibilityRole="button" accessibilityState={{ disabled: disabled || busy }} disabled={disabled || busy} onPress={work} style={[styles.button, busy || disabled ? styles.disabled : null]}><Text style={styles.buttonText}>{label}</Text></Pressable>;
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.safe} behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView contentContainerStyle={styles.screen} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>PRIVATE PORTFOLIO EDITOR</Text><Text style={styles.title}>Curate your professional story</Text><Text style={styles.copy}>Only information you write here can appear publicly. Dashboard records and your account email are never copied.</Text>
    {error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}{message ? <Text accessibilityRole="summary">{message}</Text> : null}
    {button("Reload saved draft", () => void perform(() => service.getDraft(ownerId), "Latest draft loaded. Unsaved edits were replaced."))}
    {button("Save private draft", () => { if (draft !== null) void perform(() => service.saveDraft(ownerId, content, draft.revision), "Private draft saved."); }, draft === null)}
    {draft === null ? <Text>{error ? "Reload to recover the draft." : "Loading portfolio…"}</Text> : <>
      <View style={styles.card}><Text style={styles.heading}>Profile & biography</Text>{PORTFOLIO_PROFILE_FIELDS.map(({ key, label }) => <View style={styles.field} key={key}><Text style={styles.label}>{label}</Text><TextInput editable={!busy} accessibilityLabel={label} multiline={key === "biography"} style={[styles.input, key === "biography" ? styles.multiline : null]} value={content.profile[key]} onChangeText={(value) => setContent({ ...content, profile: { ...content.profile, [key]: value } })} /></View>)}<Text style={styles.label}>Resume HTTPS link</Text><TextInput editable={!busy} accessibilityLabel="Resume link" autoCapitalize="none" style={styles.input} value={content.resumeUrl} onChangeText={(value) => setContent({ ...content, resumeUrl: value })} /></View>
      {PORTFOLIO_SECTIONS.map((section) => <View style={styles.card} key={section.key}><Text style={styles.heading}>{section.title}</Text>{section.key === "educationHighlights" ? <Text style={styles.copy}>Add only achievements you explicitly choose to share. Academic records are never imported automatically.</Text> : null}{section.key === "contactLinks" ? <Text style={styles.copy}>A mailto address appears publicly only if you explicitly enter it here.</Text> : null}{content[section.key].length === 0 ? <Text style={styles.copy}>No {section.title.toLowerCase()} added.</Text> : null}
        {content[section.key].map((entry, index) => <View style={styles.entry} key={entry.id}><Text style={styles.label}>{section.title} {index + 1}</Text>{PORTFOLIO_ENTRY_FIELDS.map(({ key, label }) => <View style={styles.field} key={key}><Text style={styles.label}>{key === "title" ? section.itemLabel : key === "subtitle" ? section.subtitleLabel : label}</Text><TextInput editable={!busy} accessibilityLabel={`${section.title} ${index + 1} ${label}`} multiline={key === "description"} style={styles.input} value={entry[key]} onChangeText={(value) => setContent(updatePortfolioEntry(content, section.key, entry.id, key, value))} /></View>)}{button(`Remove ${section.title.toLowerCase()} ${index + 1}`, () => setContent({ ...content, [section.key]: content[section.key].filter((row) => row.id !== entry.id) }))}</View>)}
        {button(`Add ${section.title.toLowerCase()}`, () => setContent({ ...content, [section.key]: [...content[section.key], service.createEntry()] }))}
      </View>)}
      <View style={styles.card}><Text style={styles.heading}>Publication controls</Text><Text style={styles.copy}>{draft.publication === null ? "No public snapshot is prepared." : `Snapshot prepared ${draft.publication.publishedAt}. Later draft edits remain private.`}</Text><Text style={styles.copy}>The public page remains unavailable until the operator explicitly enables publication on the server. Saving a draft does not publish it.</Text><Text style={styles.label}>Type PUBLISH PORTFOLIO {ownerId}</Text><TextInput editable={!busy} accessibilityLabel="Publication confirmation" style={styles.input} autoCapitalize="none" value={confirmation} onChangeText={setConfirmation} />
        {button("Prepare public snapshot", () => void perform(async () => { const saved = await service.saveDraft(ownerId, content, draft.revision); apply(saved); return service.preparePublication(ownerId, saved.revision, confirmation); }, "Curated snapshot prepared. Server publication configuration still applies."))}
        {button("Unpublish", () => void perform(() => service.unpublish(ownerId, draft.revision), "Public snapshot removed."), draft.publication === null)}
      </View>
    </>}
  </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#f3f5f2" }, screen: { padding: 20, paddingBottom: 70, gap: 16 }, eyebrow: { color: "#355f56", fontWeight: "800", letterSpacing: 1 }, title: { color: "#173b35", fontSize: 30, fontWeight: "900" }, copy: { color: "#52645f", lineHeight: 22 }, card: { backgroundColor: "#fff", borderRadius: 18, padding: 18, gap: 14 }, heading: { fontSize: 20, fontWeight: "800", color: "#173b35" }, field: { gap: 8 }, label: { color: "#173b35", fontWeight: "700" }, input: { minHeight: 48, padding: 12, borderColor: "#899f97", borderWidth: 1, borderRadius: 10, color: "#173b35" }, multiline: { minHeight: 120, textAlignVertical: "top" }, button: { minHeight: 48, backgroundColor: "#173b35", padding: 14, justifyContent: "center", borderRadius: 10 }, buttonText: { color: "#fff", fontWeight: "800" }, disabled: { opacity: .55 }, error: { color: "#852622", padding: 12, backgroundColor: "#fff0ef", borderRadius: 10 }, entry: { padding: 14, borderWidth: 1, borderColor: "#c9d8d2", borderRadius: 12, gap: 12 } });
